// Contenido editorial de Limpiezas Lumis.
// Texto de demostración: confirmar alcance, métodos y condiciones con Lumis antes de publicar.

export const business = {
  name: 'Limpiezas Lumis',
  phone: '652 63 09 38',
  phoneIntl: '+34652630938',
  whatsapp: '34652630938',
  landline: '976 05 35 43',
  landlineIntl: '+34976053543',
  email: 'lumis.arellano25@gmail.com',
  instagram: 'https://www.instagram.com/lumis.arellano25/',
  instagramHandle: '@lumis.arellano25',
  tiktok: 'https://www.tiktok.com/@lumis2848',
  tiktokHandle: '@lumis2848',
  city: 'Zaragoza',
  // Radio de trabajo indicado por Lumis: hasta unos 40 minutos de Zaragoza.
  zone: 'Zaragoza y hasta 40 min alrededor',
  zoneMinutes: 40,
  // Primer aniversario (octubre de 2026): aviso en la cinta superior y sección en Quiénes somos. Poner false para quitar el aviso.
  anniversary: true,
  // Datos del titular para el aviso legal y la política de privacidad (LSSI y RGPD).
  owner: 'Luis Hernando Arellano',
  nif: 'Y9171718E',
  address: 'Calle Monasterio de Siresa, 34, local 19, 50002 Zaragoza',
  hosting: { name: 'GitHub, Inc.', country: 'Estados Unidos' },
  legalUpdated: '30 de septiembre de 2026',
  // Lanzamiento: con launched = true la web usa el dominio propio y se genera el archivo CNAME para GitHub Pages.
  domain: 'limpiezaslumis.es',
  launched: true,
};

// Servicios que la clienta quiere destacar, en este orden (portada, reserva rápida y tarjeta de WhatsApp).
export const destacados = ['comunidades', 'gimnasios', 'oficinas', 'colegios', 'clinicas-dentales'];

export const groups = [
  { id: 'hogar', label: 'Tu hogar', img: 'viviendas', line: 'Pequeños detalles, grandes sensaciones.' },
  { id: 'exterior', label: 'Exteriores y cristal', img: 'terrazas', line: 'Más luz. Más ganas de disfrutar.' },
  { id: 'profesional', label: 'Empresas y comunidades', img: 'oficinas', line: 'El cuidado también habla de ti.' },
  { id: 'superficies', label: 'Suelos', img: 'pulido', line: 'Cada material tiene su historia.' },
];

export const services = [
  {
    slug: 'cristales', label: 'Cristales', title: 'Limpieza de cristales', img: 'cristales', category: 'exterior', compare: 'cristales', video: 'lumis-trabajo',
    line: 'Que entre toda la luz.',
    card: 'Ventanas, ventanales, cerramientos y mamparas sin marcas, con marcos y guías incluidos.',
    tags: ['Ventanas', 'Cerramientos', 'Escaparates'],
    lead: 'Cristales transparentes por dentro y por fuera, con marcos, guías y juntas limpios. Es el servicio que más se nota nada más abrir la persiana.',
    facts: ['Interior y exterior', 'Marcos y guías', 'Hasta 3 m de altura'],
    intro: [
      'Un cristal limpio cambia por completo una estancia: entra más luz, los colores se ven como son y las vistas vuelven a ser protagonistas. El polvo urbano, la lluvia, la contaminación y la cal dejan una película que, con el tiempo, apaga cualquier espacio.',
      'En Lumis trabajamos cada hoja de cristal con productos específicos y herramientas profesionales —pértigas telescópicas, raquetas, mojadores y paños de microfibra— para que el acabado sea uniforme y sin cercos. Y no nos quedamos en el vidrio: limpiamos también marcos, guías de correderas y alféizares, que es donde se acumula la suciedad que vuelve a manchar.',
      'Atendemos pisos, cerramientos de terraza, galerías acristaladas, locales comerciales, escaparates y oficinas en Zaragoza. Antes de empezar revisamos contigo el acceso a cada ventana para decidir la forma más segura de trabajar. Trabajamos hasta unos 3 metros de altura: por encima de esa altura no realizamos el servicio.',
    ],
    includes: [
      'Limpieza del cristal por ambas caras, hasta 3 metros de altura y con acceso seguro',
      'Marcos de aluminio, PVC o madera con el producto adecuado',
      'Guías y carriles de ventanas correderas, aspirados y repasados',
      'Alféizares, vierteaguas y repisas interiores',
      'Cerramientos de terraza y galerías acristaladas',
      'Mamparas y divisiones de vidrio interiores',
      'Retirada de restos de cal, polvo urbano y marcas de lluvia',
      'Secado final sin cercos ni huellas',
    ],
    ideal: [
      ['Pisos y casas', 'Ventanas de todas las estancias, balconeras y cerramientos que ya no dejan pasar la luz como antes.'],
      ['Comercios y escaparates', 'Tu escaparate es tu carta de presentación: un vidrio impecable invita a entrar.'],
      ['Oficinas y despachos', 'Ventanales y mamparas interiores limpios para trabajar con luz natural.'],
      ['Mudanzas y fin de obra', 'Cristales con restos de silicona, pintura o polvo de obra antes de entrar a vivir.'],
    ],
    steps: [
      ['Revisión del acceso', 'Valoramos cada ventana y cerramiento, comprobamos que está a menos de 3 metros de altura y elegimos cómo trabajar de forma segura.'],
      ['Protección y preparación', 'Retiramos lo imprescindible del alféizar y protegemos el suelo de la zona.'],
      ['Limpieza en profundidad', 'Mojador y producto específico, raqueta profesional y repaso de marcos y guías.'],
      ['Acabado y repaso final', 'Secado a contraluz para asegurar que no quedan marcas ni cercos.'],
    ],
    frequency: [
      ['Mensual', 'Escaparates, locales y oficinas con mucho paso de clientes.'],
      ['Trimestral', 'La opción más habitual en viviendas de ciudad.'],
      ['Puntual', 'Cambio de estación, mudanza, fin de obra o una ocasión especial.'],
    ],
    tips: [
      ['Evita el sol directo', 'Limpiar el cristal a pleno sol seca el producto demasiado rápido y deja marcas.'],
      ['Microfibra siempre', 'Para el mantenimiento entre visitas, un paño de microfibra seco evita rayas y pelusas.'],
      ['Guías despejadas', 'Aspirar las guías de vez en cuando hace que las correderas sigan deslizando bien.'],
    ],
    faq: [
      ['¿Limpiáis los cristales por fuera?', 'Sí, siempre que el acceso sea seguro: desde el interior, desde la terraza o con escalera o pértiga. Si una ventana no es accesible, te lo diremos antes de empezar.'],
      ['¿Hasta qué altura trabajáis?', 'Hasta unos 3 metros de altura. Por encima de esa altura no realizamos el trabajo: si tus ventanas o tu cristalera son más altas, te lo diremos al ver las fotos, antes de darte presupuesto.'],
      ['¿Qué incluye exactamente el servicio?', 'Cristal por ambas caras, marcos, guías y alféizares. Si quieres añadir mamparas, persianas o cerramientos, lo indicamos en el presupuesto.'],
      ['¿Necesito estar en casa?', 'Lo ideal es que alguien nos abra y nos indique las zonas prioritarias. Luego puedes seguir con tu día.'],
      ['¿Cuánto tiempo tardáis?', 'Depende del número de ventanas y del acceso. Con unas fotos te damos una estimación antes de agendar.'],
      ['¿Hacéis limpiezas periódicas?', 'Sí. Puedes programar limpiezas mensuales o trimestrales para tener los cristales siempre a punto sin tener que acordarte.'],
    ],
    related: ['persianas', 'toldos', 'fachadas'],
  },
  {
    slug: 'toldos', label: 'Toldos', title: 'Limpieza de toldos', img: 'toldos', category: 'exterior', compare: 'toldos',
    line: 'Vuelve a mirar hacia fuera.',
    card: 'Lonas, brazos y cofres sin polvo, manchas de humedad ni excrementos de aves.',
    tags: ['Lona', 'Estructura', 'Cofre'],
    lead: 'Recuperamos el color de tu toldo y alargamos su vida útil. Limpieza cuidadosa de la lona, la estructura y el cofre con productos que respetan el tejido.',
    facts: ['Lona y estructura', 'Tratamiento suave', 'Terrazas y locales'],
    intro: [
      'El toldo pasa todo el año a la intemperie: sol, polvo, lluvia, hojas, polen y excrementos de aves. Con el tiempo aparecen manchas oscuras, moho en los pliegues y una capa gris que apaga el color original. Además, la suciedad acumulada acelera el desgaste del tejido.',
      'Trabajamos la lona con productos adecuados para tejidos acrílicos y de poliéster, cepillos de cerda suave y un aclarado controlado, sin agresiones que dañen la tela o el tratamiento impermeable.',
      'Limpiamos también los brazos articulados, el cofre, el tubo de enrollado y la zona de pared donde se ancla, para que al recoger el toldo no se vuelva a ensuciar. Atendemos toldos de viviendas, áticos, bares, restaurantes y locales en Zaragoza.',
    ],
    includes: [
      'Cepillado en seco para retirar polvo, hojas y telarañas',
      'Lavado de la lona por ambas caras con producto específico para tejidos',
      'Tratamiento de manchas de humedad, moho y excrementos de aves',
      'Aclarado controlado para no dejar restos de producto',
      'Limpieza de brazos articulados y soportes',
      'Cofre, tubo de enrollado y faldón',
      'Repaso de la pared y el suelo afectados por el agua',
      'Secado completo antes de recoger el toldo',
    ],
    ideal: [
      ['Terrazas y balcones', 'Toldos extensibles y verticales que llevan años sin una limpieza a fondo.'],
      ['Áticos', 'Grandes superficies de lona expuestas al sol y al viento durante todo el año.'],
      ['Bares y restaurantes', 'El toldo de tu terraza es lo primero que ven tus clientes.'],
      ['Comercios', 'Toldos de fachada con el logotipo y los colores de tu marca.'],
    ],
    steps: [
      ['Revisión del tejido', 'Identificamos el tipo de lona, su estado y las manchas más persistentes.'],
      ['Limpieza en seco', 'Retiramos el polvo y los restos sueltos antes de aplicar agua.'],
      ['Lavado y tratamiento', 'Producto específico, cepillo suave y trabajo por zonas en las manchas difíciles.'],
      ['Aclarado y secado', 'Aclaramos, dejamos secar por completo y revisamos la estructura.'],
    ],
    frequency: [
      ['Anual', 'Al inicio de la primavera, antes de la temporada de uso.'],
      ['Semestral', 'Toldos de hostelería o en zonas con mucho polvo o árboles.'],
      ['Puntual', 'Manchas de humedad, moho o después de un invierno recogido.'],
    ],
    tips: [
      ['Nunca lo recojas mojado', 'Deja que se seque extendido: guardarlo húmedo es la causa principal de moho.'],
      ['Sin agua a presión', 'Una hidrolimpiadora doméstica puede dañar las costuras y el tratamiento de la tela.'],
      ['Retira las hojas', 'Un cepillado suave cada pocas semanas evita que la suciedad se incruste.'],
    ],
    faq: [
      ['¿Hace falta desmontar el toldo?', 'En la mayoría de los casos no. Lo limpiamos instalado, extendido y trabajando por zonas.'],
      ['¿Se pueden quitar las manchas de moho?', 'Muchas mejoran notablemente con el tratamiento adecuado. Las muy antiguas pueden dejar una marca más clara; te lo diremos al ver las fotos.'],
      ['¿Estropea los colores?', 'Usamos productos pensados para tejidos de exterior y evitamos lejías o disolventes que decoloren la lona.'],
      ['¿Limpiáis toldos de locales comerciales?', 'Sí, toldos de fachada, terrazas de hostelería y marquesinas de lona.'],
      ['¿Qué necesito para pedir presupuesto?', 'Las medidas aproximadas del toldo, si es accesible desde terraza o desde la calle y un par de fotos.'],
    ],
    related: ['terrazas', 'cristales', 'limpieza-general'],
  },
  {
    slug: 'garajes', label: 'Garajes', title: 'Limpieza de garajes', img: 'garajes', category: 'profesional', compare: 'garajes',
    line: 'Cuidado desde la entrada.',
    card: 'Plazas, rampas, accesos y trasteros sin polvo, grasa ni manchas de aceite.',
    tags: ['Comunidades', 'Rampas', 'Plazas'],
    lead: 'Garajes comunitarios y particulares limpios, seguros y agradables. Barrido, fregado mecánico y tratamiento de manchas de grasa y aceite en plazas, rampas y accesos.',
    facts: ['Comunidades y particulares', 'Manchas de aceite', 'Maquinaria profesional'],
    intro: [
      'El garaje es la primera y la última impresión de muchos edificios. Polvo que entra con los coches, barro en invierno, manchas de aceite y neumático, telarañas en los techos y papeles en las esquinas: todo se acumula rápido y da sensación de abandono.',
      'Trabajamos con barrido, aspirado y fregado adaptado a la superficie —hormigón, pintura epoxi o terrazo— y tratamos las manchas de grasa con productos desengrasantes específicos.',
      'Nos coordinamos con la comunidad o la administración de fincas para avisar a los vecinos y organizar el trabajo por zonas, de modo que los coches se puedan mover con el menor trastorno posible.',
    ],
    includes: [
      'Barrido y aspirado de plazas, calles de circulación y rampas',
      'Fregado del pavimento con maquinaria o de forma manual',
      'Tratamiento desengrasante de manchas de aceite y neumático',
      'Limpieza de sumideros y rejillas accesibles',
      'Retirada de telarañas en techos, conductos y esquinas',
      'Puertas de acceso, pulsadores y señalética',
      'Pasillos de trasteros y cuartos comunes',
      'Escaleras y vestíbulos de acceso al garaje',
    ],
    ideal: [
      ['Comunidades de vecinos', 'Garajes comunitarios con limpieza periódica o una limpieza a fondo anual.'],
      ['Administradores de fincas', 'Un proveedor que se coordina con la comunidad y avisa con antelación.'],
      ['Garajes particulares', 'Tu garaje de casa ordenado y sin manchas, listo para usarlo como taller o almacén.'],
      ['Empresas y parkings', 'Aparcamientos de oficinas, naves y locales con tránsito diario.'],
    ],
    steps: [
      ['Planificación', 'Acordamos fecha y zonas con la comunidad para que los vecinos puedan mover los coches.'],
      ['Retirada de polvo', 'Barrido y aspirado de suciedad suelta, hojas y papeles.'],
      ['Desengrasado y fregado', 'Tratamiento de manchas y fregado del pavimento por sectores.'],
      ['Detalles y revisión', 'Rejillas, puertas, rampas y repaso final de todas las zonas.'],
    ],
    frequency: [
      ['Mensual', 'Mantenimiento de garajes comunitarios con mucho uso.'],
      ['Trimestral', 'Garajes pequeños o con poco tránsito.'],
      ['Anual a fondo', 'Fregado completo y tratamiento de manchas, ideal tras el invierno.'],
    ],
    tips: [
      ['Cartón bajo el motor', 'Si tu coche pierde aceite, un cartón o bandeja evita manchas permanentes.'],
      ['Avisa con tiempo', 'Colocar el aviso en el portal una semana antes facilita mucho la limpieza.'],
      ['Ventilación', 'Mantener las rejillas despejadas reduce el polvo y la humedad.'],
    ],
    faq: [
      ['¿Hay que sacar todos los coches?', 'No necesariamente. Podemos trabajar por zonas y acordar con la comunidad un horario para mover los vehículos.'],
      ['¿Se quitan las manchas de aceite?', 'Las recientes suelen salir muy bien. Las antiguas y absorbidas por el hormigón mejoran mucho, aunque pueden dejar sombra.'],
      ['¿Trabajáis con administradores de fincas?', 'Sí. Podemos preparar el presupuesto para la junta y coordinar fechas con la administración.'],
      ['¿Limpiáis también los trasteros?', 'Los pasillos y zonas comunes, sí. El interior de trasteros privados se puede añadir si el propietario lo solicita.'],
      ['¿Qué datos necesitáis?', 'Número aproximado de plazas o metros, número de plantas y si hay manchas especialmente difíciles.'],
    ],
    related: ['comunidades', 'naves', 'pulido-suelos'],
  },
  {
    slug: 'terrazas', label: 'Terrazas', title: 'Limpieza de terrazas', img: 'terrazas', category: 'exterior', compare: 'terrazas',
    line: 'Tu rincón al aire libre.',
    card: 'Suelos exteriores, barandillas, jardineras y mobiliario listos para disfrutar.',
    tags: ['Suelos', 'Barandillas', 'Mobiliario'],
    lead: 'Devolvemos a tu terraza las ganas de salir: suelos sin verdín ni manchas, barandillas relucientes y mobiliario listo para usar.',
    facts: ['Suelos exteriores', 'Barandillas y muros', 'Mobiliario de exterior'],
    intro: [
      'La terraza es un pedazo de calle dentro de casa: recibe polvo, hojas, polen, excrementos de palomas y la humedad que deja el invierno. Cuando llega el buen tiempo, apetece usarla, pero antes hay que ponerla a punto.',
      'Limpiamos suelos de gres, baldosa hidráulica, piedra o madera exterior con el producto adecuado a cada material, retiramos verdín y manchas y dejamos los desagües despejados. También barandillas, muros, jardineras y mobiliario de exterior.',
      'Si tu terraza tiene cerramiento o toldo, podemos combinar el servicio con la limpieza de cristales y de toldos para que todo el espacio quede a punto en una sola visita.',
    ],
    includes: [
      'Barrido y retirada de hojas, polvo y restos',
      'Fregado del suelo con producto adaptado al material',
      'Tratamiento de verdín, manchas de humedad y excrementos de aves',
      'Limpieza de sumideros y desagües',
      'Barandillas de vidrio, metal o forja',
      'Muros, zócalos y jardineras por fuera',
      'Mobiliario de exterior: mesas, sillas y tumbonas',
      'Combinable con limpieza de cristales y toldos',
    ],
    ideal: [
      ['Inicio de temporada', 'Ponemos la terraza a punto para primavera y verano.'],
      ['Áticos y terrazas grandes', 'Superficies amplias que requieren tiempo y herramientas adecuadas.'],
      ['Hostelería', 'Terrazas de bares y restaurantes que tienen que lucir cada día.'],
      ['Antes de un evento', 'Una comida familiar, una celebración o una visita importante.'],
    ],
    steps: [
      ['Despejamos la zona', 'Retiramos y agrupamos el mobiliario para trabajar el suelo completo.'],
      ['Limpieza en seco', 'Barrido, hojas y restos, prestando atención a esquinas y desagües.'],
      ['Fregado y tratamiento', 'Producto según el material y trabajo específico en manchas y verdín.'],
      ['Detalles y colocación', 'Barandillas, jardineras y mobiliario limpio y colocado en su sitio.'],
    ],
    frequency: [
      ['Estacional', 'Al comienzo de la primavera y al final del verano.'],
      ['Mensual', 'Terrazas de hostelería o con mucho uso.'],
      ['Puntual', 'Antes de un evento o tras una obra en el edificio.'],
    ],
    tips: [
      ['Desagües libres', 'Revisa los sumideros tras cada tormenta para evitar balsas de agua.'],
      ['Macetas con plato', 'Los platos bajo las macetas evitan las manchas de óxido y tierra en el suelo.'],
      ['Funda para muebles', 'Cubrir el mobiliario en invierno alarga su vida y reduce la limpieza.'],
    ],
    faq: [
      ['¿Qué suelos limpiáis?', 'Gres, cerámica, baldosa hidráulica, piedra natural, cemento y tarima exterior, cada uno con su producto.'],
      ['¿Quitáis el verdín?', 'Sí, lo tratamos con productos específicos y cepillado. En zonas muy húmedas conviene repetir el mantenimiento.'],
      ['¿Limpiáis también el toldo y el cerramiento?', 'Sí, se pueden combinar en la misma visita. Indícalo al pedir cita y lo incluimos en el presupuesto.'],
      ['¿Necesito tener toma de agua?', 'Es muy recomendable disponer de un grifo en la terraza o cerca. Si no la hay, lo organizamos contigo.'],
      ['¿Cuánto cuesta?', 'El precio es a consultar: depende de los metros, del estado y de los extras. Con unas fotos lo hablamos y acordamos el precio contigo, sin compromiso.'],
    ],
    related: ['toldos', 'cristales', 'limpieza-general'],
  },
  {
    slug: 'fachadas', label: 'Fachadas y grafitis', title: 'Limpieza de fachadas y grafitis', img: 'fachadas', category: 'exterior', compare: 'fachadas',
    line: 'La cara de tu edificio, como nueva.',
    card: 'Grafitis, pintadas, carteles y suciedad en fachadas, portales y locales, hasta 3 metros de altura.',
    tags: ['Grafitis', 'Locales', 'Portales'],
    lead: 'Eliminamos grafitis, pintadas, carteles y la suciedad acumulada en fachadas de locales, portales, muros y vallas. Trabajamos a pie de calle, hasta unos 3 metros de altura.',
    facts: ['Eliminación de grafitis', 'Locales, portales y muros', 'Hasta 3 m de altura'],
    intro: [
      'La fachada es lo primero que ve cualquiera que pasa por delante. Un grafiti en el cierre de un local, carteles pegados en un portal o un zócalo ennegrecido por la contaminación dan sensación de abandono, aunque el interior esté impecable.',
      'Eliminamos grafitis y pintadas con productos específicos para cada material —piedra, ladrillo, hormigón, azulejo, metal o superficies pintadas— y retiramos carteles, restos de cola, manchas de humedad, verdín y la suciedad que deja el día a día de la calle. Siempre hacemos antes una prueba en una zona pequeña para comprobar cómo responde la superficie.',
      'Trabajamos a pie de calle, hasta unos 3 metros de altura: plantas bajas, fachadas de locales comerciales, portales, zócalos, muros, vallas y cierres metálicos. Por encima de esa altura no realizamos el trabajo; si tu fachada es más alta, te lo diremos al ver las fotos.',
    ],
    includes: [
      'Eliminación de grafitis y pintadas con productos adecuados a cada superficie',
      'Retirada de carteles, pegatinas y restos de cola',
      'Limpieza de la suciedad por contaminación, polvo y manchas de humedad',
      'Tratamiento de verdín, moho y excrementos de aves',
      'Zócalos, muros, vallas y medianeras a pie de calle',
      'Fachadas y escaparates de locales comerciales',
      'Cierres y persianas metálicas de locales',
      'Aclarado final y recogida del agua y los residuos',
    ],
    ideal: [
      ['Comercios y locales', 'Grafitis en el cierre metálico o en la fachada que dan mala imagen desde primera hora.'],
      ['Comunidades de vecinos', 'Portales, zócalos y muros de la finca a pie de calle.'],
      ['Naves y empresas', 'Muros exteriores, vallas y accesos de la instalación.'],
      ['Viviendas unifamiliares', 'Planta baja, muros de la parcela y vallas.'],
    ],
    steps: [
      ['Fotos y diagnóstico', 'Vemos el tipo de superficie, la pintura del grafiti y la altura: trabajamos hasta unos 3 metros.'],
      ['Prueba en una zona pequeña', 'Comprobamos cómo responde el material antes de tratar toda la superficie.'],
      ['Limpieza y eliminación', 'Aplicamos el producto adecuado y retiramos la pintura o la suciedad por zonas, con agua a presión controlada cuando la superficie lo permite.'],
      ['Aclarado y revisión', 'Aclaramos, recogemos los residuos y revisamos el resultado contigo.'],
    ],
    frequency: [
      ['Cuanto antes', 'Un grafiti reciente sale mucho mejor que uno que lleva meses.'],
      ['Anual', 'Limpieza general de la fachada de locales y portales.'],
      ['Puntual', 'Antes de una inauguración, una venta o la junta de la comunidad.'],
    ],
    tips: [
      ['Actúa rápido', 'Cuanto antes se limpia un grafiti, menos penetra la pintura en el material.'],
      ['No lo tapes con cualquier pintura', 'Un parche de otro color suele llamar más la atención que la propia pintada.'],
      ['Guarda fotos', 'Si la pintada se repite, las fotos ayudan a la comunidad o al seguro a gestionarlo.'],
    ],
    faq: [
      ['¿Hasta qué altura trabajáis?', 'Hasta unos 3 metros: plantas bajas, portales, locales, muros y vallas. No realizamos trabajos en fachadas de varias plantas ni por encima de esa altura.'],
      ['¿Sale el grafiti por completo?', 'Depende del material y del tiempo que lleve. En superficies lisas suele salir muy bien; en piedra o ladrillo porosos puede quedar una sombra. Te lo diremos al ver las fotos.'],
      ['¿Se puede estropear la fachada?', 'Hacemos siempre una prueba previa y usamos el producto y la presión adecuados a cada superficie para no dañarla.'],
      ['¿Limpiáis cierres metálicos de locales?', 'Sí, cierres y persianas metálicas con grafitis o con suciedad acumulada.'],
      ['¿Qué necesito para pedir presupuesto?', 'Unas fotos de la zona, las medidas aproximadas, el tipo de superficie si lo sabes y la altura hasta la que llega la pintada o la suciedad.'],
    ],
    related: ['cristales', 'comunidades', 'persianas'],
  },
  {
    slug: 'pisos-viviendas', label: 'Pisos y viviendas', title: 'Limpieza de pisos y viviendas', img: 'viviendas', category: 'hogar', compare: 'interiores',
    line: 'Qué gusto estar en casa.',
    card: 'Limpieza periódica o a fondo de cocina, baños, dormitorios y zonas comunes de tu casa.',
    tags: ['Periódica', 'A fondo', 'Mudanzas'],
    lead: 'Llega a casa y encuéntrala lista. Limpieza de pisos y viviendas, periódica o a fondo, adaptada a tu ritmo y a lo que de verdad te importa.',
    facts: ['Periódica o puntual', 'Cocina y baños a fondo', 'Entrada y salida de pisos'],
    intro: [
      'Entre el trabajo, la familia y todo lo demás, la limpieza de casa es de lo primero que se queda pendiente. Nosotros nos ocupamos para que tu tiempo libre sea realmente libre.',
      'Ofrecemos limpiezas periódicas —semanales, quincenales o mensuales— y limpiezas a fondo puntuales: cambio de estación, antes o después de una mudanza, al terminar un alquiler o después de una reforma. En cada visita seguimos un orden de trabajo de arriba abajo y de dentro afuera para que el resultado sea homogéneo.',
      'Cocina y baños reciben una atención especial: grasa, cal y juntas son lo que más se nota. Y siempre respetamos tus indicaciones sobre materiales delicados, productos que prefieras y zonas que no quieras que toquemos.',
    ],
    includes: [
      'Polvo en muebles, estanterías, rodapiés, puertas e interruptores',
      'Cocina: encimera, frentes, azulejos, fregadero, exterior de electrodomésticos',
      'Baños: sanitarios, ducha o bañera, mampara, grifería y espejos',
      'Aspirado y fregado de todos los suelos',
      'Cristales interiores y espejos',
      'Cambio de ropa de cama si lo solicitas',
      'Opcional: interior de horno, nevera y armarios',
      'Opcional: limpieza de fin de obra o mudanza',
    ],
    ideal: [
      ['Familias con poco tiempo', 'Una limpieza periódica que mantiene la casa en orden semana tras semana.'],
      ['Mudanzas', 'Deja el piso antiguo impecable y entra en el nuevo con todo limpio.'],
      ['Propietarios de alquiler', 'Pisos listos entre inquilinos o para visitas y fotografías.'],
      ['Personas mayores', 'Ayuda con las tareas más pesadas para vivir con más comodidad.'],
    ],
    steps: [
      ['Nos cuentas tu casa', 'Metros, habitaciones, baños y lo que más te preocupa.'],
      ['Plan a tu medida', 'Definimos tareas, frecuencia y los extras que quieras incluir.'],
      ['Limpieza ordenada', 'De arriba abajo, estancia por estancia, con productos adecuados a cada superficie.'],
      ['Revisión contigo', 'Repasamos el resultado y ajustamos lo necesario para la próxima visita.'],
    ],
    frequency: [
      ['Semanal', 'Casas con niños, mascotas o mucho movimiento.'],
      ['Quincenal', 'El equilibrio perfecto para la mayoría de los hogares.'],
      ['A fondo', 'Una vez por temporada o en mudanzas.'],
    ],
    tips: [
      ['Despeja superficies', 'Recoger objetos antes de la visita permite dedicar más tiempo a limpiar a fondo.'],
      ['Ventila a diario', 'Diez minutos de ventilación reducen polvo, humedad y olores.'],
      ['Juntas secas', 'Secar la ducha tras usarla evita la cal y el moho en las juntas.'],
    ],
    faq: [
      ['¿Lleváis vuestros productos?', 'Sí, llevamos productos y útiles profesionales. Si prefieres que usemos los tuyos, dínoslo sin problema.'],
      ['¿Puedo tener siempre al mismo equipo?', 'En las limpiezas periódicas intentamos mantener a las mismas personas para que conozcan tu casa.'],
      ['¿Hacéis limpiezas de mudanza?', 'Sí, tanto de entrada como de salida, incluyendo interior de armarios, cocina y electrodomésticos.'],
      ['¿Qué pasa si quiero cambiar el día?', 'Avísanos con antelación por WhatsApp y buscamos otro hueco.'],
      ['¿Hacéis limpiezas periódicas?', 'Sí: semanales, quincenales o mensuales, adaptadas a tu ritmo y siempre con el mismo orden de trabajo para que el resultado sea homogéneo.'],
    ],
    related: ['limpieza-general', 'cristales', 'abrillantado-suelos'],
  },
  {
    slug: 'persianas', label: 'Persianas', title: 'Limpieza de persianas', img: 'persianas', category: 'hogar', compare: 'persianas',
    line: 'Luz limpia, lama a lama.',
    card: 'Persianas enrollables, venecianas y mallorquinas limpias por ambas caras, con sus guías.',
    tags: ['Enrollables', 'Venecianas', 'Guías'],
    lead: 'Limpiamos persianas enrollables, venecianas y mallorquinas lama a lama, por ambas caras y con sus guías, para que suban y bajen mejor y dejen pasar una luz limpia.',
    facts: ['Lama a lama', 'Guías incluidas', 'Hasta 3 m de altura'],
    intro: [
      'Las persianas son de lo que más polvo acumula en una casa y de lo que menos se limpia. Entre las lamas se queda la suciedad de la calle, la grasa de la cocina y la humedad, y con el tiempo las guías se ensucian tanto que cuesta subirlas y bajarlas.',
      'Las limpiamos lama a lama, por ambas caras, con el producto adecuado para cada material —PVC, aluminio o madera— y aspiramos y repasamos las guías. Así la persiana queda limpia por dentro y por fuera y vuelve a funcionar con suavidad.',
      'Trabajamos desde el interior y, cuando se puede acceder con seguridad desde un balcón, una terraza o una escalera, también por fuera, siempre hasta unos 3 metros de altura. Lo más práctico es combinarlo con la limpieza de cristales en la misma visita.',
    ],
    includes: [
      'Limpieza de las lamas por ambas caras',
      'Guías laterales aspiradas y limpias',
      'Persianas enrollables de PVC y aluminio',
      'Venecianas de interior, lama a lama',
      'Mallorquinas y contraventanas',
      'Cierres metálicos de locales comerciales',
      'Repaso de la cinta, la manivela y el marco de la ventana',
      'Combinable con la limpieza de cristales en la misma visita',
    ],
    ideal: [
      ['Hogares', 'Persianas que llevan años acumulando polvo y cuesta subir.'],
      ['Mudanzas y alquileres', 'Para entrar o entregar un piso con todo a punto.'],
      ['Oficinas y consultas', 'Venecianas de despachos, salas de reuniones y salas de espera.'],
      ['Comercios', 'Cierres metálicos que dan la bienvenida cada mañana.'],
    ],
    steps: [
      ['Revisión', 'Vemos el tipo de persiana, su estado y el acceso por fuera, siempre hasta unos 3 metros de altura.'],
      ['Limpieza en seco', 'Retiramos el polvo y la suciedad suelta de lamas y guías.'],
      ['Lavado lama a lama', 'Producto adecuado al material y paño de microfibra por ambas caras.'],
      ['Secado y prueba', 'Secamos y subimos y bajamos la persiana para comprobar que funciona bien.'],
    ],
    frequency: [
      ['Semestral', 'Junto con la limpieza de cristales de primavera y otoño.'],
      ['Anual', 'Lo habitual en la mayoría de viviendas.'],
      ['Puntual', 'Mudanzas, fin de obra o antes de una ocasión especial.'],
    ],
    tips: [
      ['Un repaso rápido', 'Pasar un plumero o un paño seco cada pocas semanas evita que el polvo se incruste.'],
      ['Guías limpias', 'Aspirar las guías hace que la persiana suba y baje con menos esfuerzo.'],
      ['Nada abrasivo', 'Los estropajos y productos agresivos dañan el acabado del PVC y del aluminio.'],
    ],
    faq: [
      ['¿Hace falta desmontar la persiana?', 'En la mayoría de los casos no: la limpiamos montada, desde dentro y, si se puede acceder, desde fuera.'],
      ['¿Limpiáis la cara exterior?', 'Sí, cuando se puede acceder con seguridad desde el balcón, la terraza o una escalera, hasta unos 3 metros de altura.'],
      ['¿Qué tipos de persiana limpiáis?', 'Enrollables de PVC y aluminio, venecianas, mallorquinas y cierres metálicos de locales.'],
      ['¿Se puede hacer junto con los cristales?', 'Sí, y es lo más habitual: se hace todo en la misma visita.'],
      ['¿Qué necesito para pedir presupuesto?', 'El número de persianas, el tipo y si son accesibles desde fuera. Con unas fotos, mejor.'],
    ],
    related: ['cristales', 'pisos-viviendas', 'interiores'],
  },
  {
    slug: 'limpieza-general', label: 'Limpieza general', title: 'Limpieza general', img: 'general', category: 'hogar', compare: 'interiores',
    line: 'Una nueva sensación de orden.',
    card: 'Un repaso completo de cualquier espacio: polvo, suelos, cocina, baños y superficies.',
    tags: ['Hogar', 'Locales', 'Puntual'],
    lead: 'Cuando no sabes por dónde empezar, empezamos nosotros. Un repaso completo y ordenado para que cualquier espacio vuelva a estar a punto.',
    facts: ['Cualquier espacio', 'Puntual o periódica', 'Plan a medida'],
    intro: [
      'La limpieza general es nuestro servicio más versátil. Sirve para una vivienda, un local, un estudio o una segunda residencia que lleva tiempo cerrada. La idea es sencilla: dejar el espacio limpio, ordenado y agradable de principio a fin.',
      'Empezamos siempre por conocer el espacio y tus prioridades. A partir de ahí organizamos el trabajo por zonas: primero polvo y superficies altas, después cocina y baños, y por último suelos. Así nada se vuelve a ensuciar una vez limpio.',
      'Es la opción perfecta para una primera visita: nos permite conocer el espacio y, si quieres, proponerte después un plan de mantenimiento periódico.',
    ],
    includes: [
      'Retirada de polvo en superficies, muebles y elementos decorativos',
      'Limpieza de puertas, marcos, interruptores y rodapiés',
      'Cocina: encimeras, frentes, fregadero y azulejos',
      'Baños completos con desincrustado de cal',
      'Espejos y cristales interiores',
      'Aspirado de alfombras y fregado de suelos',
      'Vaciado de papeleras y retirada de residuos',
      'Ventilación y repaso final de olores',
    ],
    ideal: [
      ['Segundas residencias', 'Pisos o casas que llevan meses cerradas y hay que poner a punto.'],
      ['Antes de una visita', 'Familia, invitados o una fecha especial en casa.'],
      ['Locales pequeños', 'Estudios, consultas o tiendas que necesitan un repaso completo.'],
      ['Primera toma de contacto', 'Conocer el espacio antes de pasar a un plan periódico.'],
    ],
    steps: [
      ['Recorrido inicial', 'Vemos el espacio y marcamos las prioridades contigo.'],
      ['De arriba abajo', 'Polvo y superficies altas antes que nada.'],
      ['Zonas húmedas', 'Cocina y baños con productos específicos para grasa y cal.'],
      ['Suelos y cierre', 'Aspirado, fregado y revisión final estancia por estancia.'],
    ],
    frequency: [
      ['Puntual', 'Cuando lo necesites, sin compromiso de continuidad.'],
      ['Mensual', 'Un repaso completo para mantener el espacio siempre a punto.'],
      ['Estacional', 'Cuatro veces al año, con cada cambio de temporada.'],
    ],
    tips: [
      ['Haz una lista', 'Anotar las zonas que más te preocupan nos ayuda a priorizar.'],
      ['Menos objetos', 'Cuantas menos cosas haya sobre las superficies, más rápido y mejor limpiamos.'],
      ['Un paño para cada zona', 'Usar paños distintos para cocina y baño evita mezclar suciedad.'],
    ],
    faq: [
      ['¿Qué diferencia hay con la limpieza a fondo?', 'La general es un repaso completo del espacio. La limpieza a fondo añade interior de armarios, electrodomésticos, techos y otros detalles que llevan más tiempo.'],
      ['¿Limpiáis locales además de viviendas?', 'Sí, estudios, consultas, tiendas y pequeños despachos.'],
      ['¿Cuánto dura una limpieza general?', 'Depende del tamaño y del estado. Con los metros y unas fotos te damos una estimación.'],
      ['¿Puedo añadir tareas extra?', 'Claro. Plancha, interior de armarios o electrodomésticos se pueden sumar al presupuesto.'],
      ['¿Tengo que estar presente?', 'Solo al inicio para abrir y comentar prioridades. Después puedes dejarnos trabajar tranquilamente.'],
    ],
    related: ['pisos-viviendas', 'interiores', 'desinfeccion-interiores'],
  },
  {
    slug: 'interiores', label: 'Interiores', title: 'Limpieza integral de interiores', img: 'interiores', category: 'hogar', compare: 'interiores',
    line: 'Cuidar el conjunto importa.',
    card: 'Limpieza a fondo de cada estancia: techos, armarios, electrodomésticos y rincones olvidados.',
    tags: ['A fondo', 'Armarios', 'Fin de obra'],
    lead: 'La limpieza más completa para tu interior. Llegamos a los rincones que normalmente se quedan fuera: techos, lámparas, dentro de armarios y detrás de los muebles.',
    facts: ['Limpieza a fondo', 'Rincones olvidados', 'Fin de obra y mudanzas'],
    intro: [
      'La limpieza integral de interiores va un paso más allá de la limpieza habitual. Es el servicio que eliges cuando quieres empezar de cero: después de una reforma, al entrar a vivir, al terminar un alquiler o simplemente una vez al año para dejarlo todo impecable.',
      'Trabajamos estancia por estancia, desde el techo hasta el suelo: telarañas, lámparas, rejillas de ventilación, marcos de puertas, interior de armarios y cajones, electrodomésticos por dentro, azulejos, juntas y rodapiés.',
      'Es un trabajo detallado que requiere tiempo y organización, por eso lo planificamos contigo con antelación y te damos un presupuesto cerrado según el tamaño y el estado del espacio.',
    ],
    includes: [
      'Techos, esquinas, lámparas y rejillas de ventilación',
      'Paredes lavables, puertas y marcos',
      'Interior y exterior de armarios, cajones y estanterías',
      'Interior de horno, microondas, nevera y campana',
      'Azulejos y juntas de cocina y baños',
      'Detrás y debajo de muebles accesibles',
      'Radiadores, rodapiés, enchufes e interruptores',
      'Cristales interiores, espejos y suelos a fondo',
    ],
    ideal: [
      ['Fin de obra o reforma', 'Polvo fino por todas partes, restos de pintura y silicona.'],
      ['Entrada a una vivienda', 'Empieza tu nueva etapa en un espacio completamente limpio.'],
      ['Salida de un alquiler', 'Deja el piso listo para la entrega de llaves.'],
      ['Limpieza anual', 'Una puesta a punto completa una vez al año.'],
    ],
    steps: [
      ['Visita o fotos', 'Valoramos el tamaño y el estado para planificar el tiempo necesario.'],
      ['Techo y alturas', 'Empezamos por arriba: techos, lámparas y partes altas de muebles.'],
      ['Interior de muebles', 'Armarios, cajones y electrodomésticos por dentro y por fuera.'],
      ['Superficies y suelos', 'Paredes, juntas, rodapiés y suelos para terminar.'],
    ],
    frequency: [
      ['Anual', 'Una limpieza integral al año mantiene el hogar en perfecto estado.'],
      ['Puntual', 'Obras, mudanzas o cambios de inquilino.'],
      ['Combinada', 'Integral una vez y mantenimiento periódico después.'],
    ],
    tips: [
      ['Vacía los armarios', 'Si quieres el interior de armarios a fondo, lo ideal es que estén vacíos.'],
      ['Desconecta la nevera', 'Si vamos a limpiarla por dentro, conviene vaciarla y desconectarla antes.'],
      ['Espera tras la obra', 'Deja asentar el polvo fino uno o dos días después de terminar la reforma.'],
    ],
    faq: [
      ['¿Cuánto tarda una limpieza integral?', 'Normalmente una jornada completa para un piso medio, pero depende mucho del estado. Te lo confirmamos antes.'],
      ['¿Retiráis escombros de obra?', 'Retiramos la suciedad y restos de limpieza. Escombros y materiales de obra deben retirarse antes.'],
      ['¿Limpiáis el interior de los electrodomésticos?', 'Sí: horno, microondas, campana y nevera se incluyen en la limpieza integral.'],
      ['¿Se puede hacer con muebles?', 'Sí, limpiamos alrededor, encima y debajo de los muebles que se pueden mover con seguridad.'],
      ['¿Hacéis presupuesto cerrado?', 'Sí. Con los metros, el estado y algunas fotos te damos un presupuesto sin compromiso.'],
    ],
    related: ['pisos-viviendas', 'desinfeccion-interiores', 'limpieza-general'],
  },
  {
    slug: 'desinfeccion-interiores', label: 'Desinfección', title: 'Desinfección de interiores', img: 'desinfeccion', category: 'hogar',
    line: 'Tranquilidad en cada superficie.',
    card: 'Limpieza e higienización de superficies de contacto en hogares, oficinas y locales.',
    tags: ['Superficies de contacto', 'Hogar', 'Negocios'],
    lead: 'Limpieza e higienización de las superficies que más se tocan, con productos adecuados y un método ordenado para hogares, oficinas y locales.',
    facts: ['Superficies de contacto', 'Productos adecuados', 'Hogar y empresa'],
    intro: [
      'Hay superficies que tocamos decenas de veces al día sin darnos cuenta: pomos, interruptores, mandos, teclados, barandillas, grifos. La desinfección de interiores se centra en ellas para aportar un plus de higiene y tranquilidad.',
      'Nuestro método siempre sigue dos pasos: primero limpiamos para eliminar la suciedad visible y después aplicamos el producto higienizante respetando su tiempo de actuación. Sin limpieza previa, ningún producto funciona como debe.',
      'Es un servicio que se puede hacer de forma puntual —tras una enfermedad en casa, al entrar en una vivienda o antes de reabrir un local— o incorporar al mantenimiento de oficinas, consultas y gimnasios.',
    ],
    includes: [
      'Limpieza previa de todas las superficies a tratar',
      'Pomos, tiradores, interruptores y mandos',
      'Encimeras, mesas, sillas y reposabrazos',
      'Baños completos: sanitarios, grifería y accesorios',
      'Barandillas, pasamanos y botoneras',
      'Teclados, teléfonos y equipos de uso compartido (con producto adecuado)',
      'Aplicación de producto higienizante respetando su tiempo de actuación',
      'Ventilación del espacio al finalizar',
    ],
    ideal: [
      ['Tras una enfermedad en casa', 'Una limpieza extra de las zonas y superficies más utilizadas.'],
      ['Consultas y centros', 'Espacios que reciben público y necesitan un protocolo de higiene.'],
      ['Oficinas y coworkings', 'Puestos compartidos, salas de reuniones y office.'],
      ['Entrada a una vivienda', 'Empezar de cero en un espacio que ha estado habitado por otras personas.'],
    ],
    steps: [
      ['Identificamos los puntos clave', 'Localizamos las superficies de más contacto de tu espacio.'],
      ['Limpieza previa', 'Eliminamos la suciedad visible; es imprescindible para higienizar.'],
      ['Higienización', 'Aplicamos el producto adecuado y respetamos su tiempo de actuación.'],
      ['Ventilación y cierre', 'Ventilamos el espacio y dejamos las superficies listas para usar.'],
    ],
    frequency: [
      ['Puntual', 'Tras una enfermedad, una mudanza o antes de una reapertura.'],
      ['Semanal', 'Consultas, gimnasios y espacios con mucho público.'],
      ['Integrada', 'Como parte del mantenimiento habitual de tu oficina o local.'],
    ],
    tips: [
      ['Primero limpiar', 'Un producto higienizante sobre una superficie sucia pierde eficacia.'],
      ['Respeta los tiempos', 'Cada producto necesita un tiempo de contacto para actuar: no lo retires antes.'],
      ['Ventila siempre', 'Abrir ventanas después de limpiar renueva el aire y elimina olores.'],
    ],
    faq: [
      ['¿Qué productos utilizáis?', 'Productos higienizantes de uso profesional adecuados a cada superficie. Si tienes alguna sensibilidad o preferencia, coméntanoslo antes.'],
      ['¿Es seguro para niños y mascotas?', 'Seguimos las indicaciones de uso de cada producto y ventilamos al terminar. Te indicaremos cuándo puedes volver a usar cada zona.'],
      ['¿Tengo que salir de casa?', 'Normalmente no es necesario salir, aunque sí conviene no estar en la estancia mientras trabajamos.'],
      ['¿Lo hacéis en oficinas y locales?', 'Sí, de forma puntual o como parte de un plan de mantenimiento.'],
      ['¿Se puede combinar con otra limpieza?', 'Sí, es habitual combinarlo con una limpieza general o integral en la misma visita.'],
    ],
    related: ['interiores', 'oficinas', 'gimnasios'],
  },
  {
    slug: 'oficinas', label: 'Oficinas', title: 'Limpieza de oficinas', img: 'oficinas', category: 'profesional',
    line: 'Un buen lugar para trabajar.',
    card: 'Mantenimiento diario o semanal de puestos, salas, office y aseos, adaptado a tu horario.',
    tags: ['Mantenimiento', 'Fuera de horario', 'Despachos'],
    lead: 'Una oficina limpia se nota en el equipo y en las visitas. Mantenimiento periódico adaptado a tu horario para que tu espacio de trabajo esté siempre a punto.',
    facts: ['Adaptado a tu horario', 'Mantenimiento periódico', 'Puestos, office y aseos'],
    intro: [
      'Pasamos muchas horas en la oficina, y un espacio limpio y ordenado influye directamente en cómo nos sentimos y en la imagen que damos a clientes y visitas.',
      'Diseñamos un plan de limpieza a medida según el tamaño de la oficina, el número de personas y el uso de cada zona: puestos de trabajo, salas de reuniones, recepción, office o cocina y aseos. Podemos trabajar antes de que abráis, al cierre o en el horario que mejor os encaje.',
      'Mantenemos siempre las mismas pautas y, en lo posible, al mismo equipo, para que conozca vuestro espacio y vuestras preferencias. Cualquier ajuste lo gestionamos contigo de forma directa por WhatsApp o teléfono.',
    ],
    includes: [
      'Polvo en mesas, estanterías y equipos (sin mover documentación)',
      'Vaciado de papeleras y separación de residuos',
      'Salas de reuniones y recepción',
      'Office o cocina: encimera, fregadero, microondas y mesas',
      'Aseos completos con reposición de consumibles si se nos facilitan',
      'Aspirado de moquetas y fregado de suelos',
      'Cristales interiores, mamparas y puertas de vidrio',
      'Higienización de pomos, interruptores y superficies de contacto',
    ],
    ideal: [
      ['Despachos profesionales', 'Abogados, gestorías, arquitectos y asesorías.'],
      ['Startups y coworkings', 'Espacios abiertos con puestos compartidos y mucho movimiento.'],
      ['Consultas y clínicas', 'Salas de espera y zonas de atención al público.'],
      ['Oficinas de empresa', 'Plantas completas con varias zonas y necesidades.'],
    ],
    steps: [
      ['Visita y necesidades', 'Conocemos la oficina, el horario y las zonas prioritarias.'],
      ['Plan de limpieza', 'Tareas por frecuencia: diarias, semanales y mensuales.'],
      ['Puesta en marcha', 'Empezamos con una primera limpieza a fondo para partir de cero.'],
      ['Seguimiento', 'Revisamos contigo cómo va y ajustamos lo que haga falta.'],
    ],
    frequency: [
      ['Diaria', 'Oficinas con mucho personal o atención al público.'],
      ['2-3 veces por semana', 'La opción más habitual en despachos medianos.'],
      ['Semanal', 'Oficinas pequeñas o con poca ocupación.'],
    ],
    tips: [
      ['Mesas despejadas', 'Una política de mesa limpia permite limpiar mejor cada puesto.'],
      ['Office ordenado', 'Pedir a cada persona que friegue su taza reduce mucho la acumulación.'],
      ['Comunica cambios', 'Avísanos de reuniones o visitas importantes y reforzamos la limpieza.'],
    ],
    faq: [
      ['¿Podéis limpiar fuera del horario de oficina?', 'Sí, trabajamos a primera hora, al cierre o en el horario que acordemos.'],
      ['¿Tocáis los documentos o equipos?', 'No movemos documentación. En equipos informáticos limpiamos solo el exterior con productos adecuados.'],
      ['¿Hay contrato de permanencia?', 'Lo acordamos contigo. Preferimos ganarnos la continuidad con el resultado.'],
      ['¿Reponéis papel y jabón?', 'Sí, si nos facilitáis los consumibles o lo incluimos como servicio adicional.'],
      ['¿Hacéis una limpieza a fondo inicial?', 'Es lo recomendable: partir de cero hace que el mantenimiento sea mucho más eficaz.'],
    ],
    related: ['cristales', 'desinfeccion-interiores', 'abrillantado-suelos'],
  },
  {
    slug: 'gimnasios', label: 'Gimnasios', title: 'Limpieza de gimnasios', img: 'gimnasios', category: 'profesional',
    line: 'Espacios que invitan a moverse.',
    card: 'Salas, máquinas, vestuarios y duchas limpios e higienizados para tus clientes.',
    tags: ['Vestuarios', 'Máquinas', 'Salas'],
    lead: 'En un gimnasio la limpieza es parte del servicio que das a tus clientes. Salas, máquinas, vestuarios y duchas higienizados y agradables cada día.',
    facts: ['Vestuarios y duchas', 'Máquinas y material', 'Fuera de horario'],
    intro: [
      'Sudor, humedad y mucho tránsito: los gimnasios, boxes y estudios de yoga o pilates necesitan una limpieza específica y constante. La primera impresión de un socio al entrar en el vestuario puede decidir si renueva o no.',
      'Trabajamos las zonas húmedas con productos antical y antimoho, higienizamos las superficies de contacto del material —agarres, bancos, colchonetas— y dejamos los suelos técnicos limpios con el producto adecuado para cada tipo de pavimento.',
      'Organizamos el servicio fuera de las horas punta o con el centro cerrado para no interferir con las clases ni con los entrenamientos.',
    ],
    includes: [
      'Vestuarios: bancos, taquillas por fuera, espejos y suelos',
      'Duchas y aseos con tratamiento antical y antimoho',
      'Higienización de agarres, bancos y superficies de máquinas',
      'Colchonetas, esterillas y material de sala',
      'Suelos técnicos, de caucho o tarima con el producto adecuado',
      'Espejos de sala y cristales',
      'Recepción, zona de espera y fuentes de agua',
      'Vaciado de papeleras y control de olores',
    ],
    ideal: [
      ['Gimnasios', 'Salas de musculación, cardio y actividades dirigidas.'],
      ['Boxes de entrenamiento', 'Mucho material, suelos de caucho y magnesio en todas partes.'],
      ['Estudios de yoga y pilates', 'Espacios tranquilos donde la limpieza se nota especialmente.'],
      ['Centros deportivos', 'Instalaciones con vestuarios de gran uso.'],
    ],
    steps: [
      ['Mapa de zonas', 'Definimos zonas húmedas, salas y material con sus prioridades.'],
      ['Horario sin clases', 'Planificamos el trabajo para no interferir con la actividad.'],
      ['Limpieza e higienización', 'Primero limpieza, después higienización de superficies de contacto.'],
      ['Control continuo', 'Revisión periódica de resultados y ajustes con la dirección.'],
    ],
    frequency: [
      ['Diaria', 'Vestuarios, duchas y superficies de contacto.'],
      ['Semanal', 'Limpieza más a fondo de salas, espejos y material.'],
      ['Mensual', 'Tratamiento de juntas, rejillas y zonas poco accesibles.'],
    ],
    tips: [
      ['Pulverizadores en sala', 'Poner a disposición de los socios producto y papel ayuda a mantener el material.'],
      ['Ventilación del vestuario', 'Un extractor en marcha reduce la humedad y el moho.'],
      ['Toalla obligatoria', 'Pedir toalla en las máquinas reduce el sudor en las superficies.'],
    ],
    faq: [
      ['¿Trabajáis con el gimnasio abierto?', 'Preferimos hacerlo en horas valle o con el centro cerrado, pero nos adaptamos a vuestro horario.'],
      ['¿Qué productos usáis en las máquinas?', 'Productos adecuados para tapicerías sintéticas, metal y plásticos, que no deterioran el material.'],
      ['¿Limpiáis suelos de caucho?', 'Sí, con productos específicos que no dejan el suelo resbaladizo.'],
      ['¿Os encargáis de los olores?', 'Una limpieza correcta de desagües, juntas y textiles es la base para controlarlos.'],
      ['¿Hacéis limpieza inicial a fondo?', 'Sí, es lo recomendable antes de empezar un plan de mantenimiento.'],
    ],
    related: ['desinfeccion-interiores', 'oficinas', 'pulido-suelos'],
  },
  {
    slug: 'comunidades', label: 'Comunidades', title: 'Limpieza de comunidades', img: 'comunidades', category: 'profesional',
    line: 'Lo compartido también es tuyo.',
    card: 'Portales, escaleras, ascensores y zonas comunes limpios con un calendario fijo.',
    tags: ['Portales', 'Escaleras', 'Ascensores'],
    lead: 'Portales que dan gusto, escaleras relucientes y ascensores impecables. Un calendario fijo y un trato directo con la comunidad y la administración.',
    facts: ['Calendario fijo', 'Portal, escaleras y ascensor', 'Trato con administradores'],
    intro: [
      'Las zonas comunes son la carta de presentación de un edificio y el espacio que comparten todos los vecinos. Un portal cuidado revaloriza la finca y hace que llegar a casa sea más agradable.',
      'Establecemos un calendario fijo de limpieza con las tareas de cada visita y las que se hacen de forma periódica —cristales del portal, puertas, buzones, barandillas, cuartos de contadores— para que todo esté siempre a punto sin sorpresas.',
      'Trabajamos directamente con el presidente o presidenta de la comunidad o con la administración de fincas, y ofrecemos servicios complementarios como la limpieza del garaje o el abrillantado del suelo del portal.',
    ],
    includes: [
      'Portal: suelo, felpudos, buzones, puertas y cristales',
      'Escaleras y rellanos: barrido y fregado',
      'Barandillas, pasamanos y pomos',
      'Ascensor: cabina, espejo, botoneras y puertas',
      'Cristales de portal y ventanas de escalera',
      'Retirada de telarañas y polvo en techos y lámparas',
      'Cuartos de contadores y de basuras accesibles',
      'Opcional: garaje, trasteros y abrillantado del portal',
    ],
    ideal: [
      ['Comunidades de vecinos', 'Edificios de cualquier tamaño con portal y escaleras.'],
      ['Administradores de fincas', 'Un proveedor fiable con comunicación directa y ágil.'],
      ['Urbanizaciones', 'Zonas comunes, accesos y cuartos de instalaciones.'],
      ['Edificios de oficinas', 'Vestíbulos y zonas comunes con mucho tránsito.'],
    ],
    steps: [
      ['Visita al edificio', 'Recorremos las zonas comunes y valoramos necesidades.'],
      ['Propuesta para la junta', 'Presupuesto claro con tareas y frecuencias.'],
      ['Calendario fijo', 'Días y horarios estables que los vecinos conocen.'],
      ['Comunicación directa', 'Cualquier incidencia se resuelve rápido por WhatsApp o teléfono.'],
    ],
    frequency: [
      ['1-2 veces por semana', 'Lo más habitual en comunidades medianas.'],
      ['Diaria', 'Grandes edificios o con mucho tránsito.'],
      ['Mensual / trimestral', 'Cristales, barandillas a fondo y techos.'],
    ],
    tips: [
      ['Felpudo en la entrada', 'Un buen felpudo retiene gran parte de la suciedad que entra al portal.'],
      ['Horario de basuras', 'Respetar el horario del cuarto de basuras evita olores en las zonas comunes.'],
      ['Cuadrante visible', 'Un cartel con los días de limpieza ayuda a los vecinos a respetar el suelo mojado.'],
    ],
    faq: [
      ['¿Preparáis presupuesto para la junta?', 'Sí, detallado por tareas y frecuencias para que la comunidad pueda valorarlo.'],
      ['¿Qué pasa si un día no se puede limpiar?', 'Lo comunicamos con antelación y recuperamos la visita en otro día acordado.'],
      ['¿Limpiáis también el garaje de la comunidad?', 'Sí, se puede incluir de forma periódica o como limpieza a fondo anual.'],
      ['¿Os encargáis de sacar los cubos?', 'Es un servicio que se puede añadir; lo concretamos con la comunidad.'],
      ['¿Trabajáis en toda Zaragoza?', 'Trabajamos en Zaragoza capital y hasta unos 40 minutos alrededor: área metropolitana, polígonos, centros comerciales y pueblos cercanos. Más lejos no nos desplazamos, porque el viaje encarecería el servicio. Si dudas, pregúntanos por tu zona.'],
    ],
    related: ['garajes', 'fachadas', 'cristales'],
  },
  {
    slug: 'naves', label: 'Naves', title: 'Limpieza de naves', img: 'naves', category: 'profesional',
    line: 'Grandes espacios, gran atención.',
    card: 'Naves industriales, almacenes y talleres: suelos, oficinas, vestuarios y zonas de carga.',
    tags: ['Industrial', 'Almacenes', 'Talleres'],
    lead: 'Limpieza de naves industriales, almacenes y talleres adaptada a la actividad. Suelos, zonas de carga, oficinas y vestuarios sin parar tu producción.',
    facts: ['Grandes superficies', 'Sin parar la actividad', 'Suelos industriales'],
    intro: [
      'Una nave limpia es una nave más segura y eficiente: menos polvo en la mercancía y en la maquinaria, menos riesgo de resbalones y una mejor imagen ante clientes, proveedores y auditorías.',
      'Adaptamos el trabajo a la actividad de cada instalación —logística, taller, almacén o producción— y lo planificamos en turnos o en horarios de menor actividad. Utilizamos barrido mecánico y fregado de gran superficie cuando el espacio lo requiere.',
      'No solo limpiamos el área de trabajo: también oficinas, vestuarios, comedor, aseos y accesos, para que toda la instalación esté a la altura.',
    ],
    includes: [
      'Barrido y fregado de grandes superficies',
      'Tratamiento de manchas de aceite y grasa en el pavimento',
      'Zonas de carga, muelles y accesos',
      'Pasillos, estanterías y zonas de almacenaje accesibles',
      'Oficinas, recepción y salas de reuniones',
      'Vestuarios, aseos y comedor del personal',
      'Cristales, puertas y ventanales accesibles',
      'Limpieza de fin de obra en naves nuevas',
    ],
    ideal: [
      ['Almacenes logísticos', 'Mucho movimiento de carretillas y polvo en suspensión.'],
      ['Talleres', 'Grasa, aceite y virutas en suelos y zonas de trabajo.'],
      ['Naves de producción', 'Limpieza compatible con los turnos y la normativa interna.'],
      ['Naves nuevas', 'Limpieza de fin de obra antes de empezar a operar.'],
    ],
    steps: [
      ['Visita técnica', 'Conocemos la actividad, los riesgos y las zonas prioritarias.'],
      ['Planificación por turnos', 'Organizamos el trabajo sin interferir en la producción.'],
      ['Limpieza con maquinaria', 'Barrido y fregado adaptados al pavimento industrial.'],
      ['Zonas del personal', 'Vestuarios, comedor, aseos y oficinas para completar.'],
    ],
    frequency: [
      ['Diaria / semanal', 'Mantenimiento de zonas de trabajo y del personal.'],
      ['Mensual', 'Limpieza a fondo de pavimento y estanterías.'],
      ['Puntual', 'Fin de obra, auditoría o cambio de actividad.'],
    ],
    tips: [
      ['Pasillos despejados', 'Mantener las zonas de paso libres acelera mucho el barrido mecánico.'],
      ['Absorbente a mano', 'Tener material absorbente cerca evita que los derrames se extiendan.'],
      ['Señaliza zonas', 'Marcar las zonas de limpieza en curso mejora la seguridad de todos.'],
    ],
    faq: [
      ['¿Podéis trabajar en fin de semana?', 'Sí, adaptamos el horario para no interrumpir la actividad.'],
      ['¿Limpiáis maquinaria industrial?', 'Limpiamos exteriores y entornos de maquinaria. La limpieza técnica interna depende del equipo y se valora caso a caso.'],
      ['¿Qué tamaño de nave atendéis?', 'Desde pequeños talleres hasta naves de gran superficie. Cuéntanos los metros y te orientamos.'],
      ['¿Hacéis limpieza de fin de obra?', 'Sí, dejamos la nave lista para empezar a operar.'],
      ['¿Cómo pido presupuesto?', 'Indícanos metros, actividad, tipo de suelo y frecuencia deseada. Si hace falta, visitamos la instalación.'],
    ],
    related: ['garajes', 'pulido-suelos', 'oficinas'],
  },
  {
    slug: 'colegios', label: 'Colegios', title: 'Limpieza de colegios', img: 'colegios', category: 'profesional',
    line: 'Aulas limpias para aprender mejor.',
    card: 'Aulas, pasillos, comedor, aseos y gimnasio escolar, siempre fuera del horario de clase.',
    tags: ['Aulas', 'Comedores', 'Aseos'],
    lead: 'Limpieza diaria o periódica de colegios, escuelas infantiles y academias: aulas, pasillos, comedor, aseos y zonas comunes, siempre fuera del horario de clase.',
    facts: ['Fuera del horario lectivo', 'Aulas, aseos y comedor', 'Limpieza a fondo en vacaciones'],
    intro: [
      'En un colegio pasan cada día decenas o cientos de niños y niñas: tocan mesas, pomos, barandillas y lavabos, comen en el comedor y juegan en el patio. Un centro limpio es más agradable para aprender y transmite tranquilidad a las familias desde la puerta.',
      'Organizamos la limpieza por zonas y prioridades: aulas, pasillos y escaleras, aseos, comedor, gimnasio escolar, secretaría y sala de profesores. Prestamos especial atención a las superficies que más se tocan y a los aseos, y usamos productos adecuados para espacios con niños, siguiendo sus indicaciones de uso y ventilando al terminar.',
      'Trabajamos después de las clases o a primera hora, sin interferir con la actividad del centro, y adaptamos el plan al calendario escolar: aprovechamos las vacaciones de verano, Navidad y Semana Santa para hacer la limpieza a fondo.',
    ],
    includes: [
      'Aulas: mesas, sillas, pizarras, estanterías y suelos',
      'Pasillos, escaleras, barandillas y zonas comunes',
      'Aseos completos, con reposición de consumibles si se nos facilitan',
      'Comedor: mesas, sillas y suelos después del servicio',
      'Gimnasio escolar y vestuarios',
      'Secretaría, dirección y sala de profesores',
      'Higienización de pomos, interruptores y superficies de contacto',
      'Limpieza a fondo en vacaciones: cristales accesibles (hasta 3 m), puertas y rincones',
    ],
    ideal: [
      ['Colegios e institutos', 'Centros públicos, concertados y privados con limpieza diaria.'],
      ['Escuelas infantiles', 'Espacios con los más pequeños, donde la higiene es prioritaria.'],
      ['Academias', 'Academias de idiomas, refuerzo, música o formación.'],
      ['Centros de ocio infantil', 'Ludotecas y espacios de actividades extraescolares.'],
    ],
    steps: [
      ['Visita al centro', 'Recorremos el colegio y marcamos zonas, prioridades y horarios.'],
      ['Plan por zonas', 'Tareas diarias, semanales y de vacaciones, adaptadas al calendario escolar.'],
      ['Limpieza sin interferir', 'Trabajamos al terminar las clases o a primera hora.'],
      ['Seguimiento', 'Revisamos el resultado con la dirección y ajustamos lo que haga falta.'],
    ],
    frequency: [
      ['Diaria', 'Aulas, aseos, comedor y zonas de paso.'],
      ['Semanal', 'Cristales interiores, gimnasio y zonas de menor uso.'],
      ['Vacaciones', 'Limpieza a fondo en verano, Navidad y Semana Santa.'],
    ],
    tips: [
      ['Mesas despejadas', 'Pedir al alumnado que deje las mesas recogidas agiliza mucho la limpieza.'],
      ['Papeleras en cada aula', 'Evitan restos de comida y papeles por el suelo.'],
      ['Avisa de los eventos', 'Festivales o jornadas de puertas abiertas: reforzamos la limpieza antes y después.'],
    ],
    faq: [
      ['¿Limpiáis fuera del horario de clase?', 'Sí. Trabajamos al terminar las clases o a primera hora de la mañana, sin interferir con la actividad del centro.'],
      ['¿Qué productos utilizáis?', 'Productos profesionales adecuados para espacios con niños, siguiendo siempre sus indicaciones de uso y ventilando al terminar.'],
      ['¿Hacéis limpieza a fondo en vacaciones?', 'Sí, es el mejor momento: verano, Navidad y Semana Santa, cuando el centro está vacío.'],
      ['¿Trabajáis con escuelas infantiles y academias?', 'Sí, adaptamos el plan al tamaño del centro y a su horario.'],
      ['¿Qué necesito para pedir presupuesto?', 'Metros aproximados, número de aulas y aseos, si hay comedor o gimnasio y el horario del centro. Si hace falta, lo visitamos.'],
    ],
    related: ['oficinas', 'desinfeccion-interiores', 'gimnasios'],
  },
  {
    slug: 'clinicas-dentales', label: 'Clínicas dentales', title: 'Limpieza de clínicas dentales', img: 'clinicas', img2: 'clinicas-sala', category: 'profesional',
    line: 'Confianza desde la sala de espera.',
    card: 'Sala de espera, recepción, gabinetes, aseos y zonas de personal, fuera del horario de consulta.',
    tags: ['Sala de espera', 'Gabinetes', 'Aseos'],
    lead: 'Limpieza e higienización de clínicas dentales: sala de espera, recepción, gabinetes, aseos y zonas de personal, fuera del horario de consulta y con un orden de trabajo claro.',
    facts: ['Fuera del horario de consulta', 'Orden de trabajo por zonas', 'Superficies de contacto'],
    intro: [
      'En una clínica dental la limpieza es parte de la confianza del paciente. La sala de espera, el mostrador, los aseos y cada gabinete tienen que transmitir cuidado y orden desde el primer momento.',
      'Seguimos un orden de trabajo por zonas, de las comunes a las más sensibles, y prestamos especial atención a las superficies que más se tocan: pomos, mostradores, datáfono, sillas de la sala de espera, interruptores y lavabos. Limpiamos suelos, superficies y mobiliario de los gabinetes con productos higienizantes profesionales y respetamos siempre el protocolo propio de la clínica.',
      'El instrumental, los equipos clínicos y los residuos sanitarios los gestiona el personal de la clínica según sus protocolos; nosotros nos ocupamos del resto del espacio. Trabajamos fuera del horario de consulta para no interferir con los pacientes.',
    ],
    includes: [
      'Sala de espera: suelos, sillas, mesas y revisteros',
      'Recepción: mostrador, datáfono y zona de atención',
      'Gabinetes: suelos, superficies, lavabos y mobiliario (no instrumental ni equipos clínicos)',
      'Aseos de pacientes y de personal',
      'Vestuario, office y despachos del personal',
      'Higienización de pomos, interruptores y superficies de contacto',
      'Cristales interiores, puertas y mamparas',
      'Vaciado de papeleras de residuos comunes (los sanitarios los gestiona la clínica)',
    ],
    ideal: [
      ['Clínicas dentales', 'Clínicas con uno o varios gabinetes y sala de espera.'],
      ['Consultas y fisioterapia', 'Consultas médicas, centros de fisioterapia y psicología.'],
      ['Centros de estética', 'Cabinas, recepción y zonas de espera.'],
      ['Policlínicas', 'Centros con varias especialidades y mucho paso de pacientes.'],
    ],
    steps: [
      ['Visita y protocolo', 'Conocemos la clínica, sus zonas y el protocolo que ya siguen.'],
      ['Orden por zonas', 'De las zonas comunes a las más sensibles, para no trasladar suciedad.'],
      ['Limpieza e higienización', 'Primero limpieza, después higienización de las superficies de contacto.'],
      ['Seguimiento', 'Revisamos el resultado con la clínica y ajustamos lo que haga falta.'],
    ],
    frequency: [
      ['Diaria', 'Lo habitual: sala de espera, aseos, gabinetes y recepción al cierre.'],
      ['2-3 veces por semana', 'Clínicas pequeñas o con pocos días de consulta.'],
      ['Mensual a fondo', 'Cristales, puertas, rincones y zonas de almacenaje.'],
    ],
    tips: [
      ['Superficies despejadas', 'Cuantos menos objetos haya sobre mostradores y encimeras, mejor se higienizan.'],
      ['Residuos bien separados', 'Tener claras las papeleras de residuos comunes y sanitarios facilita el trabajo de todos.'],
      ['Ventila la sala de espera', 'Renovar el aire a diario ayuda a mantener un ambiente agradable.'],
    ],
    faq: [
      ['¿Limpiáis los gabinetes?', 'Sí: suelos, superficies, lavabos y mobiliario. El instrumental y los equipos clínicos los limpia y desinfecta el personal sanitario según su protocolo.'],
      ['¿Gestionáis los residuos sanitarios?', 'No. Los residuos sanitarios los gestiona la clínica con su gestor autorizado; nosotros nos encargamos de los residuos comunes.'],
      ['¿Trabajáis fuera del horario de consulta?', 'Sí, al cierre o a primera hora, sin coincidir con los pacientes.'],
      ['¿Qué productos utilizáis?', 'Productos higienizantes de uso profesional adecuados a cada superficie. Si la clínica tiene un protocolo o productos propios, lo seguimos.'],
      ['¿Qué necesito para pedir presupuesto?', 'Metros aproximados, número de gabinetes y aseos, días de consulta y la frecuencia que te interesa.'],
    ],
    related: ['desinfeccion-interiores', 'oficinas', 'cristales'],
  },
  {
    slug: 'pulido-suelos', label: 'Pulido de suelos', title: 'Pulido de suelos', img: 'pulido', category: 'superficies', compare: 'suelos',
    line: 'Otra mirada a tus suelos.',
    card: 'Recupera mármol, terrazo y piedra natural: eliminamos arañazos y devolvemos la uniformidad.',
    tags: ['Mármol', 'Terrazo', 'Piedra'],
    lead: 'Devolvemos la vida a suelos de mármol, terrazo y piedra natural. El pulido elimina el desgaste superficial y recupera un acabado uniforme y liso.',
    facts: ['Mármol y terrazo', 'Maquinaria profesional', 'Viviendas y portales'],
    intro: [
      'Con los años, los suelos de mármol, terrazo y piedra natural pierden su aspecto original: aparecen arañazos, zonas mates por el paso, manchas y pequeñas irregularidades. Muchas veces no hace falta cambiar el suelo; basta con pulirlo.',
      'El pulido es un trabajo con maquinaria profesional y discos o abrasivos de grano progresivo que retira una capa superficial muy fina del material. Así se eliminan marcas y desgaste y se consigue una superficie lisa y homogénea, lista para el abrillantado.',
      'Antes de empezar, analizamos el tipo de piedra, su estado y el acabado que buscas —mate, satinado o brillo— para proponerte el tratamiento más adecuado. Protegemos rodapiés y muebles y controlamos el agua y el lodo generados durante el proceso.',
    ],
    includes: [
      'Valoración del material y del estado del suelo',
      'Protección de rodapiés, puertas y mobiliario cercano',
      'Pulido con maquinaria y abrasivos de grano progresivo',
      'Tratamiento de arañazos, desgaste y zonas mates',
      'Recogida del lodo y limpieza durante el proceso',
      'Limpieza final del suelo y del entorno',
      'Recomendación de acabado: mate, satinado o brillo',
      'Combinable con abrillantado y cristalizado',
    ],
    ideal: [
      ['Viviendas con mármol o terrazo', 'Suelos de casas antiguas o reformadas que han perdido su aspecto.'],
      ['Portales de comunidad', 'Suelos de mucho tránsito que dan la bienvenida al edificio.'],
      ['Locales y oficinas', 'Recepciones y zonas de atención al público.'],
      ['Antes de entrar a vivir', 'El mejor momento: sin muebles, el resultado es más completo.'],
    ],
    steps: [
      ['Diagnóstico', 'Identificamos el tipo de piedra, el desgaste y el acabado deseado.'],
      ['Protección', 'Cubrimos rodapiés y zonas sensibles y retiramos lo necesario.'],
      ['Pulido progresivo', 'Pasadas con abrasivos de grano cada vez más fino.'],
      ['Limpieza y acabado', 'Retiramos restos y preparamos el suelo para el abrillantado.'],
    ],
    frequency: [
      ['Cada varios años', 'Un pulido suele durar mucho si se mantiene bien.'],
      ['Puntual', 'Reformas, mudanzas o cuando el suelo ha perdido su aspecto.'],
      ['Con mantenimiento', 'Abrillantados periódicos para prolongar el resultado.'],
    ],
    tips: [
      ['Fieltro en las patas', 'Protege los muebles con fieltros para evitar arañazos nuevos.'],
      ['pH neutro', 'Friega con productos de pH neutro: los ácidos y la lejía dañan el mármol.'],
      ['Felpudos en la entrada', 'La arena que traemos en los zapatos actúa como lija sobre la piedra.'],
    ],
    faq: [
      ['¿Qué diferencia hay entre pulir y abrillantar?', 'El pulido elimina desgaste y marcas retirando una capa fina del material. El abrillantado da brillo y protección sobre un suelo ya en buen estado.'],
      ['¿Se puede pulir cualquier suelo?', 'Principalmente mármol, terrazo y algunas piedras naturales. El gres y la cerámica no se pulen de la misma manera.'],
      ['¿Hace mucho ruido o polvo?', 'Trabajamos en húmedo para evitar polvo. La maquinaria sí produce algo de ruido durante el proceso.'],
      ['¿Hay que vaciar la casa?', 'No es imprescindible, pero cuanto más despejado esté el suelo, más uniforme será el resultado.'],
      ['¿Cuánto tiempo se tarda?', 'Depende de los metros y del estado. Con fotos y medidas te damos una estimación.'],
    ],
    related: ['abrillantado-suelos', 'comunidades', 'naves'],
  },
  {
    slug: 'abrillantado-suelos', label: 'Abrillantado', title: 'Abrillantado de suelos', img: 'abrillantado', category: 'superficies', compare: 'suelos',
    line: 'La luz también está bajo tus pies.',
    card: 'Brillo y protección para mármol, terrazo y piedra: un acabado que se nota nada más entrar.',
    tags: ['Brillo', 'Protección', 'Mantenimiento'],
    lead: 'Un suelo brillante transforma cualquier espacio. Abrillantado y cristalizado de mármol, terrazo y piedra para un acabado luminoso y protegido.',
    facts: ['Brillo duradero', 'Capa protectora', 'Mantenimiento periódico'],
    intro: [
      'El abrillantado es el toque final que hace que un suelo de mármol o terrazo luzca como nuevo. Refleja la luz, hace que la estancia parezca más amplia y protege la superficie frente al desgaste diario.',
      'Trabajamos con maquinaria rotativa y productos de cristalizado o abrillantado adecuados a cada piedra. Cuando el suelo está muy desgastado, recomendamos un pulido previo para que el brillo sea uniforme; si está en buen estado, el abrillantado directo es suficiente.',
      'Es un servicio muy demandado en portales de comunidad, recepciones y viviendas con suelos de piedra. Con un mantenimiento periódico, el brillo se conserva mucho más tiempo.',
    ],
    includes: [
      'Limpieza previa y desengrasado del suelo',
      'Valoración: abrillantado directo o pulido previo',
      'Cristalizado o abrillantado con maquinaria rotativa',
      'Tratamiento especial en zonas de más paso',
      'Protección de rodapiés y mobiliario cercano',
      'Repaso de juntas y esquinas',
      'Limpieza final del entorno',
      'Recomendaciones de mantenimiento',
    ],
    ideal: [
      ['Portales y escaleras', 'La primera impresión de todo el edificio.'],
      ['Viviendas con mármol', 'Salones y pasillos que recuperan toda su luz.'],
      ['Recepciones y locales', 'Espacios que tienen que transmitir cuidado y calidad.'],
      ['Mantenimiento periódico', 'Suelos pulidos que queremos conservar brillantes.'],
    ],
    steps: [
      ['Valoración del suelo', 'Comprobamos el estado y decidimos si requiere pulido previo.'],
      ['Limpieza a fondo', 'Retiramos grasa y suciedad que impedirían un buen acabado.'],
      ['Abrillantado', 'Maquinaria rotativa y producto adecuado al tipo de piedra.'],
      ['Revisión con luz', 'Comprobamos la uniformidad del brillo en toda la superficie.'],
    ],
    frequency: [
      ['Trimestral', 'Portales y zonas de mucho tránsito.'],
      ['Semestral', 'Viviendas y locales con uso moderado.'],
      ['Anual', 'Suelos con poco desgaste y buen mantenimiento.'],
    ],
    tips: [
      ['Mopa en seco', 'Retirar el polvo a diario con mopa evita que la arena raye el brillo.'],
      ['Poca agua', 'Friega con la fregona bien escurrida y productos neutros.'],
      ['Nada de ceras caseras', 'Las ceras de supermercado acumulan capas y apagan el brillo con el tiempo.'],
    ],
    faq: [
      ['¿Cuánto dura el brillo?', 'Depende del tránsito y del mantenimiento. En viviendas puede durar muchos meses con los cuidados adecuados.'],
      ['¿Puedo pisar el suelo enseguida?', 'Normalmente sí, poco después de terminar. Te indicaremos los tiempos según el producto.'],
      ['¿Sirve para gres o porcelánico?', 'El abrillantado está pensado para piedra natural y terrazo. Para gres tenemos otras soluciones de limpieza.'],
      ['¿Necesito pulir antes?', 'Solo si el suelo tiene arañazos o desgaste importante. Lo valoramos con fotos o en visita.'],
      ['¿Hacéis mantenimiento en comunidades?', 'Sí, es habitual programarlo cada trimestre o semestre junto a la limpieza del portal.'],
    ],
    related: ['pulido-suelos', 'pisos-viviendas', 'comunidades'],
  },
];

export const pillars = [
  ['Productos y técnicas de alta calidad', 'Elegimos el producto y la herramienta según cada superficie: no se limpia igual un cristal, un mármol o una lona.'],
  ['Un plan a tu medida', 'Escuchamos qué necesitas y lo convertimos en un plan claro, con tareas y frecuencia acordadas.'],
  ['Trato cercano y directo', 'Hablas directamente con nosotros por WhatsApp o teléfono. Sin centralitas ni esperas.'],
  ['Cuidamos tu espacio', 'Protegemos lo que hay alrededor, respetamos tus indicaciones y dejamos todo en su sitio.'],
];

// Reseñas reales de Google facilitadas por el cliente. Copiadas literalmente; no editar su contenido.
// `tags` indica en qué páginas de servicio se muestran.
export const reviewsUrl = 'https://share.google/y6DHE7UBpLFz16yQ7'; // ficha de Google de Limpiezas Lumis (ver opiniones)
// Enlace directo para escribir una reseña (Place ID ChIJXwrSYmsVWQ0RQTvncGR6ZM4, comprobado que corresponde a la ficha de Lumis).
export const reviewWriteUrl = 'https://search.google.com/local/writereview?placeid=ChIJXwrSYmsVWQ0RQTvncGR6ZM4';
export const reviews = [
  { name: 'Jaster66', rating: 5, tags: ['cristales', 'terrazas'], highlight: true, text: 'Tras 15 años en Valdespartera nadie había sabido limpiar los enormes cristales de mi terraza por ser de difícil acceso en el exterior. Lumis han sido los únicos que me los han dejado impecables, incluída la carpintería de aluminio y con un servicio puntual y cuidadoso. Mis vecinos ya han tomado nota. Gran trabajo y a un precio razonable.' },
  { name: 'Arevageor', rating: 5, tags: ['cristales', 'pisos-viviendas'], text: 'Un servicio impecable. Los cristales quedaron perfectos, brillantes y como nuevos. Me impresionó lo cuidadoso que fue con los suelos y todo el entorno, trabajando con una delicadeza y respeto que pocas veces se ve. Es muy puntual, profesional y muy amable. Da mucha tranquilidad contratar a una persona que se nota que cuida hasta el más mínimo detalle. ¡Muy recomendados!' },
  { name: 'T-CURA fisioterapia', rating: 5, business: true, tags: ['clinicas-dentales', 'cristales', 'oficinas'], text: 'Contamos con Limpiezas Lumis para el servicio de limpieza de cristales en nuestra clínica. Luis es un gran profesional: atento, cercano y muy detallista. Muy contentos siempre con el resultado!' },
  { name: 'Felix Chevez', rating: 5, tags: ['toldos', 'cristales', 'terrazas'], text: 'Muy contento con el servicio de limpieza de cristales y toldos, los técnicos fueron muy profesionales y amables. Los cristales quedaron impecables y el toldo luce como nuevo. Definitivamente, los recomendaría y volvería a contar con ellos para futuros trabajos.' },
  { name: 'Jimmy Santeliz', rating: 5, tags: ['limpieza-general', 'oficinas', 'desinfeccion-interiores'], text: 'Excelente servicio. Dejaron mi restaurante impecable, fueron puntuales, profesionales y muy cuidadosos con cada detalle. Sin duda volveré a contratarlos. ¡Totalmente recomendados!' },
  { name: 'Muscle Experience Entrenamiento y salud', rating: 5, business: true, tags: ['gimnasios', 'oficinas', 'cristales'], text: 'Contamos con el de forma regular tanto para limpieza del local como para cristales y estamos muy contentos. Profesionalidad y seriedad en su trabajo.' },
  { name: 'Herminia Chevez Pastrana', rating: 5, tags: ['pisos-viviendas', 'limpieza-general'], text: 'He contratado el servicio de limpieza lumis y la verdad he quedado encantada, primero que nada para mí la puntualidad es prioridad en todo y ha sido de 10👌luego cuidan cada detalle del trabajo a realizar, personas muy amables,recomendable 100% seguramente volveré a utilizar sus servicios !!' },
  { name: 'Muscle Center Zaragoza', rating: 5, business: true, tags: ['gimnasios', 'limpieza-general'], text: 'Servicio impecable, rapidez y amabilidad. Lo necesitamos para cubrir una baja, cubrió con creces todas las expectativas.' },
  { name: 'Ricardo Hernandez', rating: 5, tags: ['limpieza-general', 'cristales'], text: 'Excelente servicio y trato de Luis! Un gran profesional en limpieza general y de cristales! 100% recomendado' },
  { name: 'Ana Recuenco', rating: 5, tags: ['persianas', 'cristales', 'interiores'], text: 'Servicio excelente, limpieza de cristales, persianas , y mampara de baño,quedaron como nuevos.' },
  { name: 'Cristina G.', rating: 5, tags: ['pisos-viviendas', 'interiores'], text: 'Encantada con el servicio de Luis!!! Se esmera muchisimo en que todo quede impecable. Un gran acierto contratar sus servicios' },
  { name: 'PEDRO CAMPOS', rating: 5, tags: ['interiores', 'pisos-viviendas'], text: 'Gran Profesional y persona, Puntual y seriedad, perfecta limpieza de campana extractora, todo un acierto' },
  { name: 'viviana castro', rating: 5, tags: ['cristales'], text: 'Excelente servicio dejan tus cristales como nuevos, puntualidad y gran calidad humana el conjunto perfecto 💯% recomendable.' },
  { name: 'yosmelis chirino', rating: 5, tags: ['comunidades', 'naves'], text: 'Excelente servicio, si buscan calidad de servicio, precios accesibles y compromiso pueden contar con esta empresa sin duda alguna.' },
  { name: 'Pepita Luna', rating: 4, tags: ['pisos-viviendas'], text: 'Buen profesional,.. puntual y detallista contentos con el trabajo de limpieza de piso...muy recomendable' },
];

// ---------- Páginas: Cómo trabajamos, Opiniones y Contacto ----------
export const method = [
  ['calendar', 'Nos contactas', 'Reserva desde la web en un minuto, escríbenos por WhatsApp o llámanos. Nos cuentas qué quieres limpiar, dónde está y cuándo te vendría bien.'],
  ['camera', 'Vemos tu espacio', 'Con unas fotos y las medidas aproximadas entendemos el estado, los materiales y los accesos. Si hace falta, lo vemos en persona antes de presupuestar.'],
  ['plan', 'Presupuesto claro', 'Te enviamos una propuesta con lo que incluye el servicio, cómo lo haremos y el precio. Sin compromiso y sin letra pequeña: tú decides.'],
  ['spark', 'El día de la limpieza', 'Llegamos a la hora acordada, protegemos lo que hay alrededor y trabajamos con productos y herramientas adecuados a cada superficie.'],
  ['check', 'Revisión y seguimiento', 'Repasamos el resultado contigo antes de irnos. Si quieres, programamos las siguientes limpiezas para que tu espacio esté siempre a punto.'],
];
export const quoteChecklist = [
  'Ubicación o barrio en Zaragoza',
  'Tipo de espacio: vivienda, local, comunidad, nave…',
  'Medidas aproximadas o número de ventanas',
  'Unas fotos del estado y de los accesos',
  'Altura de ventanas y cristaleras (trabajamos hasta unos 3 metros)',
  'Qué días u horarios te vienen mejor',
];
export const commitments = [
  ['clock', 'Puntualidad', 'Llegamos cuando decimos. Es lo que más repiten nuestros clientes en sus reseñas.'],
  ['shield', 'Cuidado del entorno', 'Protegemos suelos, muebles y objetos cercanos, y lo dejamos todo en su sitio.'],
  ['drop', 'El producto adecuado', 'Cada superficie tiene su producto: vidrio, lona, mármol, aluminio, tejido u hormigón.'],
  ['wa', 'Trato directo', 'Hablas siempre con nosotros. Sin centralitas, sin esperas y sin intermediarios.'],
  ['tag', 'Sin sorpresas', 'El precio que acordamos es el que pagas. Si algo cambia, te lo contamos antes.'],
  ['heart', 'Revisión contigo', 'No nos vamos hasta que el resultado te convence.'],
];
export const tools = [
  ['Pértigas telescópicas', 'Para llegar a cristales altos y cerramientos de difícil acceso, siempre dentro de nuestro límite de 3 metros.'],
  ['Raquetas y mojadores', 'Acabado uniforme y sin marcas en ventanas, mamparas y escaparates.'],
  ['Microfibra profesional', 'Atrapa el polvo y la grasa sin rayar ni dejar pelusa.'],
  ['Maquinaria rotativa', 'Para pulir y abrillantar mármol, terrazo y piedra natural.'],
  ['Barrido y fregado mecánico', 'Grandes superficies como garajes y naves, en menos tiempo.'],
  ['Productos específicos', 'Desengrasantes, antical, higienizantes y productos para tejidos de exterior.'],
];
export const serviceModes = [
  ['Puntual', 'Una limpieza cuando la necesitas: una mudanza, fin de obra, cambio de estación o una visita especial.', 'limpieza-general'],
  ['Periódica', 'Semanal, quincenal, mensual o trimestral. Tu espacio siempre a punto sin tener que pensar en ello.', 'pisos-viviendas'],
  ['Empresas y comunidades', 'Planes de mantenimiento para oficinas, gimnasios, naves, garajes y comunidades de vecinos.', 'oficinas'],
];
export const loveThemes = [
  ['clock', 'Puntualidad', 'la puntualidad es prioridad en todo y ha sido de 10', 'Herminia Chevez Pastrana'],
  ['spark', 'Cuidado del detalle', 'se nota que cuida hasta el más mínimo detalle', 'Arevageor'],
  ['heart', 'Trato cercano', 'atento, cercano y muy detallista', 'T-CURA fisioterapia'],
  ['sun', 'Cristales impecables', 'dejan tus cristales como nuevos', 'viviana castro'],
];

export const generalFaq = [
  ['¿En qué zonas trabajáis?', 'Trabajamos en Zaragoza capital y hasta unos 40 minutos alrededor: área metropolitana, polígonos, centros comerciales y pueblos cercanos. Más lejos no nos desplazamos, porque el viaje encarecería el servicio. Si dudas, pregúntanos por tu zona.'],
  ['¿Hasta qué altura trabajáis?', 'Trabajamos hasta unos 3 metros de altura, desde el suelo, una escalera o una terraza. Por encima de esa altura no realizamos el trabajo; si tienes dudas, envíanos una foto y te lo confirmamos.'],
  ['¿Cuánto cuesta el servicio?', 'Todos nuestros precios son a consultar, porque cada espacio es distinto. Nos cuentas qué necesitas, vemos unas fotos o el espacio y acordamos contigo el precio antes de empezar, sin compromiso.'],
  ['¿Puedo agendar para hoy mismo?', 'Puedes pedir tu cita hoy mismo desde la web o por WhatsApp. Te confirmamos el primer hueco disponible.'],
  ['¿Lleváis vuestros productos y herramientas?', 'Sí, llevamos productos y útiles profesionales. Si prefieres que usemos algún producto concreto, dínoslo.'],
  ['¿Trabajáis con empresas y comunidades?', 'Sí: oficinas, gimnasios, naves, garajes y comunidades de vecinos con planes periódicos.'],
];

// ---------- Quiénes somos: la historia de Luis (según el audio de la familia, 01/10/2026) ----------
export const about = {
  timeline: [
    ['home', '2021', 'Llega a España', 'Luis llega a España en 2021 y, desde el primer momento, encuentra su sitio en el mundo de la limpieza. Es el trabajo al que dedica todos estos años.'],
    ['building', '2021 – 2025', 'Aprende el oficio en varias empresas', 'Trabaja para distintas empresas de limpieza, sobre todo en cristales y oficinas. Son años de ventanales, mamparas, escaparates y despachos en los que aprende la técnica, los productos adecuados para cada superficie y a trabajar con cuidado en espacios que no son suyos.'],
    ['spark', 'Octubre de 2025', 'Nace Limpiezas Lumis', 'Con toda esa experiencia, Luis da el paso y monta su propia empresa. La idea es sencilla: ofrecer el trabajo bien hecho que ha aprendido, con trato directo y sin intermediarios.'],
    ['star', 'Octubre de 2026', 'Cumplimos nuestro primer año', 'Un año después, Lumis cuida viviendas, comunidades, clínicas, gimnasios, restaurantes y oficinas de Zaragoza y alrededores. Y sus clientes lo cuentan en Google.'],
  ],
  story: [
    'Durante años, Luis vio la limpieza profesional desde dentro: lo que de verdad valora un cliente, lo que se nota cuando alguien trabaja con prisa y lo que marca la diferencia cuando se trabaja con cariño.',
    'Con esa experiencia decidió montar Lumis. Hoy, cuando nos contratas, hablas directamente con quien hace el trabajo: Luis te escucha, ve tu espacio, te da un presupuesto claro y se encarga de que todo quede como debe.',
  ],
  family: [
    'Luis no trabaja solo: lo hace junto a su suegra, que lleva 17 años en España. Durante todo ese tiempo ha trabajado de interna, cuidando a personas mayores en sus propias casas.',
    'Ser interna es mucho más que cuidar: es encargarse cada día de que una casa esté limpia, ordenada y en condiciones para alguien que lo necesita. Esa experiencia es la que hoy aporta a Lumis.',
    'Detrás de Lumis hay una familia que sabe lo que significa que alguien te abra la puerta de su casa o de su negocio.',
  ],
  familySkills: [
    ['home', 'Limpieza del hogar, a fondo y a diario', 'Cocinas, baños, dormitorios y zonas comunes, con la constancia de quien lo ha hecho cada día durante años.'],
    ['shield', 'Higiene y desinfección', 'Acostumbrada a casas de personas mayores, donde la limpieza también es salud.'],
    ['check', 'Orden y detalle', 'Cada cosa en su sitio y nada fuera de lugar al terminar.'],
    ['heart', 'Discreción y confianza', 'Años trabajando dentro de las casas de otras familias, con su total confianza.'],
  ],
  values: [
    ['tool', 'Oficio aprendido desde dentro', 'Años limpiando cristales y oficinas para otras empresas antes de montar la suya.'],
    ['user', 'Trato directo', 'Hablas con Luis desde el primer mensaje hasta la revisión final del trabajo.'],
    ['heart', 'Confianza en casa', 'Un equipo familiar acostumbrado a cuidar los espacios de otras personas.'],
    ['pin', 'Cerca de ti', 'Zaragoza y hasta unos 40 minutos alrededor, para darte siempre un precio justo.'],
  ],
  zone: ['Zaragoza capital y sus barrios', 'Área metropolitana', 'Polígonos y naves', 'Centros comerciales de los alrededores', 'Pueblos a menos de 40 minutos'],
};

// Texto del primer aniversario, escrito por la familia (01/10/2026).
export const anniversary = {
  title: 'Un año dejando cada espacio <em>impecable.</em>',
  text: [
    'En octubre de 2025 dimos un salto importante: convertir años de trabajo, aprendizaje y experiencia en cristales y oficinas en nuestra propia empresa de limpieza.',
    'Este octubre celebramos nuestro primer aniversario. Doce meses de esfuerzo continuo, clientes que han confiado en nosotros desde el primer día y un compromiso intacto con la calidad y la palabra dada.',
    'Gracias a quienes forman parte de este camino y a cada cliente que nos abre las puertas de su casa, su negocio o su comunidad.',
  ],
  cheer: '¡A por muchos años más dejando cada espacio impecable!',
};
