const fs=require('node:fs');
const {JSDOM}=require('./.qa/node_modules/jsdom');
const services=JSON.parse(fs.readFileSync('scripts/services.json','utf8').replace(/^\uFEFF/,''));
const arrow='<svg viewBox="0 0 24 24" class="icon" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="M5 12h14m-6-6 6 6-6 6"/></svg>';
const star='<svg viewBox="0 0 100 100" class="bloom" aria-hidden="true"><path fill="currentColor" d="M50 0C53 32 68 47 100 50 68 53 53 68 50 100 47 68 32 53 0 50 32 47 47 32 50 0Z"/></svg>';
const scenes=[['hogar','Tu casa, en calma.','Un lugar al que apetece volver.','portada','pisos-viviendas'],['negocio','Tu negocio, a punto.','El cuidado también habla de ti.','oficinas','oficinas'],['exterior','Tu rincón al sol.','Más ganas de disfrutarlo.','terrazas','terrazas']];
const photo=(name,alt)=>`<img src="assets/images/${name}.jpg" alt="${alt}" loading="lazy" decoding="async">`;
for(const file of fs.readdirSync('.').filter(n=>n.endsWith('.html'))){
 const dom=new JSDOM(fs.readFileSync(file,'utf8'));const d=dom.window.document;
 for(const el of d.querySelectorAll('[data-enhancement]'))el.remove();
 const style=d.createElement('link');style.rel='stylesheet';style.href='assets/css/experience.css?v=3';style.dataset.enhancement='style';d.head.append(style);
 const script=d.createElement('script');script.src='assets/js/experience.js?v=3';script.defer=true;script.dataset.enhancement='script';d.body.append(script);
 const progress=d.createElement('div');progress.className='reading-progress';progress.dataset.enhancement='progress';progress.setAttribute('aria-hidden','true');d.querySelector('.site-header').append(progress);
 if(file==='index.html'){
  const hero=d.querySelector('.home-hero');hero.classList.add('living-hero');
  hero.querySelector('.hero-content').innerHTML=`<div class="hero-kicker"><span></span> TU LIMPIEZA EN ZARAGOZA</div><h1>Más luz.<br>Más calma.<br><em>Más Lumis.</em></h1><p>Para tu casa, tu negocio y ese rincón<br>que quieres volver a disfrutar.<br><strong>Deja tus espacios relucientes.</strong></p><div class="hero-actions"><a class="button button-blue" href="https://wa.me/34652609338?text=${encodeURIComponent('Hola, quería pedir un presupuesto sin compromiso a Limpiezas Lumis.')}" target="_blank" rel="noopener">Hablemos de tu espacio ${arrow}</a><a class="hero-secondary" href="#presupuesto">Preparar mi consulta ${arrow}</a></div><span class="hero-micro">Sin compromiso · Una conversación contigo</span><a class="scroll-invitation" href="#servicios"><span>↓</span> Encuentra lo que necesitas</a>`;
  hero.querySelector('.hero-art').innerHTML=`<div class="scene-carousel" aria-label="Espacios para disfrutar con Lumis"><div class="scene-stage">${scenes.map(([id,title,line,img,link],i)=>`<div class="scene-panel" role="tabpanel" id="scene-${id}" aria-labelledby="tab-${id}" ${i?'hidden':''}><img src="assets/images/${img}.jpg" srcset="assets/images/${img}-sm.jpg 640w, assets/images/${img}.jpg 1536w" sizes="(max-width:760px) 95vw, 60vw" alt="${title} Ejemplo visual ilustrativo" loading="${i?'lazy':'eager'}" ${!i?'fetchpriority="high"':''}><div class="scene-caption"><span>0${i+1} / 03</span><h2>${title}</h2><p>${line}</p><a href="${link}.html">Explorar este servicio ${arrow}</a></div></div>`).join('')}<span class="scene-credit">Ejemplo visual ilustrativo</span></div><div class="scene-controls"><div class="scene-tabs" role="tablist" aria-label="Elige un espacio">${scenes.map(([id],i)=>`<button id="tab-${id}" role="tab" aria-controls="scene-${id}" aria-selected="${!i}" tabindex="${i?-1:0}" type="button">${['Tu hogar','Tu negocio','Al aire libre'][i]}</button>`).join('')}</div><button class="scene-pause" type="button" aria-label="Pausar cambio de escenas" aria-pressed="false"><span aria-hidden="true">Ⅱ</span></button></div></div><div class="living-sticker">${star}<span>Qué gusto<br><em>estar aquí.</em></span></div><div class="living-orbit" aria-hidden="true">${star}</div>`;
  const feeling=d.createElement('section');feeling.className='feeling-section section-pad';feeling.dataset.enhancement='feeling';feeling.innerHTML=`<div class="feeling-title reveal"><span class="eyebrow">EL TOQUE LUMIS</span><h2>Hay cosas que<br>se ven. Y otras<br>que <em>se sienten.</em></h2><p>Abrir las ventanas. Recibir a alguien.<br>Entrar en casa y pensar: «qué gusto».</p></div><div class="feeling-mosaic"><div class="feeling-photo reveal">${photo('general','Detalle ilustrativo de limpieza de una superficie')}<span>El cuidado empieza en los detalles.</span></div><div class="feeling-note reveal">${star}<h3>Tu espacio<br>dice mucho<br><em>de ti.</em></h3><p>Cuéntanos cómo quieres cuidarlo.</p><a href="#presupuesto" aria-label="Preparar una consulta para mi espacio">${arrow}</a></div><div class="feeling-local reveal"><span>DE AQUÍ.</span><strong>Zaragoza</strong><p>Una llamada. Un mensaje.<br>Empezamos escuchándote.</p><a href="tel:+34652609338">652 63 09 38 ${arrow}</a></div></div></section>`;
  const intro=d.querySelector('.intro-section');if(intro)intro.replaceWith(feeling);else d.querySelector('.brand-ribbon').after(feeling);
  const planner=d.createElement('section');planner.className='consultation section-pad';planner.id='presupuesto';planner.dataset.enhancement='consultation';planner.innerHTML=`<div class="consultation-copy"><span class="eyebrow light">VAMOS A PONÉRTELO FÁCIL</span><h2>Tu espacio.<br>Tus prioridades.<br><em>Empezamos aquí.</em></h2><p>Elige lo que necesitas y prepara tu consulta. La conversación continúa contigo en WhatsApp.</p><div class="consultation-signature">Sin compromiso. Sin rodeos. ${star}</div></div><form class="consultation-form" aria-label="Preparar consulta por WhatsApp"><span class="planner-kicker">CUÉNTANOS UN POCO</span><fieldset class="planner-categories"><legend>01 <span>¿Qué espacio quieres cuidar?</span></legend><div class="planner-options">${[['hogar','Mi hogar','viviendas'],['exterior','Mi exterior','terrazas'],['profesional','Mi negocio','oficinas'],['superficies','Suelos y tejidos','tapicerias']].map(([id,label,img],i)=>`<label><input type="radio" name="space" value="${id}" ${!i?'checked':''}>${photo(img,'')}<span>${label}</span><i aria-hidden="true">✓</i></label>`).join('')}</div></fieldset><div class="planner-fields"><label for="consult-service"><b>02</b> ¿Qué necesitas?</label><select id="consult-service" name="service">${services.map(s=>`<option value="${s.slug}" data-category="${s.category}" ${s.slug==='pisos-viviendas'?'selected':''}>${s.title}</option>`).join('')}</select><p class="planner-service-note" hidden>Consulta con Lumis la disponibilidad de este servicio.</p><div class="planner-location"><label for="consult-zone">Zona o barrio <span>(opcional)</span><input id="consult-zone" name="zone" type="text" maxlength="100" placeholder="Ej. Zaragoza, Centro" autocomplete="off"></label><label for="consult-size">Tamaño aproximado <span>(opcional)</span><input id="consult-size" name="size" type="text" maxlength="80" placeholder="Ej. 80 m²" autocomplete="off"></label></div></div><details class="message-preview"><summary>Ver el mensaje que vas a llevar ${arrow}</summary><label class="sr" for="consult-message">Mensaje preparado</label><textarea id="consult-message" rows="4" readonly></textarea></details><a class="button planner-send" href="https://wa.me/34652609338?text=${encodeURIComponent('Hola, quería consultar la limpieza de una vivienda en Zaragoza.')}" target="_blank" rel="noopener">Continuar en WhatsApp ${arrow}</a><small>Podrás revisar tu mensaje antes de enviarlo.</small><noscript><p>Puedes consultar todos los servicios directamente por WhatsApp.</p></noscript></form>`;
  d.querySelector('.services-section').after(planner);
  d.querySelector('.nav-cta').href='#presupuesto';
 }
 if(d.body.classList.contains('service-page')){
  const targets=[['.service-intro','el-servicio','El servicio'],['.detail-cards','detalles','Qué tener en cuenta'],['.compare-section','comparativa','Antes y después'],['.faq-section','preguntas','Tus dudas']];
  const jump=d.createElement('nav');jump.className='service-jumpnav';jump.dataset.enhancement='jumpnav';jump.setAttribute('aria-label','En esta página');
  for(const [selector,id,label] of targets){const section=d.querySelector(selector);if(section){section.id=id;jump.insertAdjacentHTML('beforeend',`<a href="#${id}">${label}</a>`);}}
  d.querySelector('.service-hero').after(jump);
 }
 for(const figure of d.querySelectorAll('.gallery-grid figure,.insta-gallery figure')){
  const img=figure.querySelector('img');if(!img || img.closest('a'))continue;
  const a=d.createElement('a');a.className='gallery-open';a.href=img.getAttribute('src');a.setAttribute('aria-label','Ampliar imagen: '+img.alt);img.before(a);a.append(img);a.insertAdjacentHTML('beforeend','<span class="gallery-zoom" aria-hidden="true">↗</span>');
 }
 const modal=d.createElement('dialog');modal.className='image-viewer';modal.dataset.enhancement='viewer';modal.setAttribute('aria-label','Galería de ejemplos visuales');modal.innerHTML=`<div class="viewer-top"><span>Una mirada más de cerca</span><button class="viewer-close" type="button" aria-label="Cerrar imagen">×</button></div><figure><img alt=""><figcaption>Ejemplo visual ilustrativo</figcaption></figure><div class="viewer-controls"><button type="button" class="viewer-prev" aria-label="Imagen anterior">←</button><span class="viewer-count" aria-live="polite"></span><button type="button" class="viewer-next" aria-label="Imagen siguiente">→</button></div>`;d.body.append(modal);
 fs.writeFileSync(file,'<!doctype html>\n'+d.documentElement.outerHTML);dom.window.close();
}
console.log('Mejoras visuales e interactivas incorporadas en las 17 páginas.');
